ServerEvents.recipes(event => {
    //Gravel
        //String
            event.recipes.gtceu.electric_sieve("gtceu:gravel_sifting_type_string")
                .notConsumable(InputItem.of('exnihilosequentia:string_mesh'))
                .itemInputs('minecraft:gravel')
                .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 1920, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 950, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.trona_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.salt_stone', 1), 925, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.rock_salt_stone', 1), 833, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lepidolite_stone', 1), 357, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.spodumene_stone', 1), 238, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tin_stone', 1), 2422, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 808, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.basaltic_mineral_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.granitic_mineral_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.fullers_earth_stone', 1), 364, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.gypsum_stone', 1), 364, 250)
                .duration(100)
                .EUt(24)
            
        //bronze
             event.recipes.gtceu.electric_sieve("gtceu:gravel_sifting_type_bronze")
                .notConsumable(InputItem.of('exnihilosequentia:flint_mesh'))
                .itemInputs('minecraft:gravel')
                .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 1920, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 950, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.trona_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.salt_stone', 1), 925, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.rock_salt_stone', 1), 833, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lepidolite_stone', 1), 357, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.spodumene_stone', 1), 238, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tin_stone', 1), 2422, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 808, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.basaltic_mineral_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.granitic_mineral_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.fullers_earth_stone', 1), 364, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.gypsum_stone', 1), 364, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.galena_stone', 1), 1040, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lead_stone', 1), 520, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.silver_stone', 1), 520, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.zeolite_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.glauconite_sand_stone', 1), 338, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.oilsands_stone', 1), 2250, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.garnet_sand_stone', 1), 432, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.asbestos_stone', 1), 432, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.diatomite_stone', 1), 144, 250)
                .duration(100)
                .EUt(24)
            
        //Gravel-End
            function gravelChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:gravel_sifting_type_${id}`)
                    .notConsumable(InputItem.of(`exnihilosequentia:${mesh}_mesh`))
                    .itemInputs('minecraft:gravel')
                    .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 1920, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 950, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.trona_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.salt_stone', 1), 925, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.rock_salt_stone', 1), 833, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lepidolite_stone', 1), 357, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.spodumene_stone', 1), 238, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tin_stone', 1), 2422, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 808, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.basaltic_mineral_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.granitic_mineral_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.fullers_earth_stone', 1), 364, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.gypsum_stone', 1), 364, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.galena_stone', 1), 1040, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lead_stone', 1), 520, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.silver_stone', 1), 520, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.zeolite_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.glauconite_sand_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.oilsands_stone', 1), 2250, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.garnet_sand_stone', 1), 432, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.asbestos_stone', 1), 432, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.diatomite_stone', 1), 144, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.platinum_stone', 1), 760, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.palladium_stone', 1), 591, boost)
                    .duration(100)
                    .EUt(24)     
            }
                //Steel
                    gravelChance('steel', 'iron', 250)
                //Aluminium
                    gravelChance('aluminium', 'diamond', 350)
                //Stainless
                    gravelChance('stainless', 'emerald', 450)
                //Titanium
                    gravelChance('titanium', 'netherite', 500)                
    //Sand
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:sand_sifting_type_bronze')
                .notConsumable(InputItem.of('exnihilosequentia:flint_mesh'))
                .itemInputs('minecraft:sand')
                .chancedOutput(Item.of('gregicsifting:chunk.copper_sand', 1), 612, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.redstone_sand', 1), 1938, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_sand', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chromite_sand', 1), 161, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrope_sand', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sapphire_sand', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.green_sapphire_sand', 1), 272, 250)
                .duration(100)
                .EUt(24)
            
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:sand_sifting_type_steel')
                .notConsumable(InputItem.of('exnihilosequentia:iron_mesh'))
                .itemInputs('minecraft:sand')
                .chancedOutput(Item.of('gregicsifting:chunk.copper_sand', 1), 612, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.redstone_sand', 1), 1938, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_sand', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chromite_sand', 1), 161, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrope_sand', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sapphire_sand', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.green_sapphire_sand', 1), 272, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_sand', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.iron_sand', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrite_sand', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_sand', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.malachite_sand', 1), 169, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.garnierite_sand', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.nickel_sand', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_sand', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_sand', 1), 182, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bentonite_sand', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.magnesite_sand', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.olivine_sand', 1), 507, 250)
                .duration(100)
                .EUt(24)
            
        //Sand-End
            function sandChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:sand_sifting_type_${id}`)
                    .notConsumable(InputItem.of(`exnihilosequentia:${mesh}_mesh`))
                    .itemInputs('minecraft:sand')
                    .chancedOutput(Item.of('gregicsifting:chunk.copper_sand', 1), 612, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.redstone_sand', 1), 1938, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_sand', 1), 646, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chromite_sand', 1), 161, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrope_sand', 1), 816, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.sapphire_sand', 1), 816, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.green_sapphire_sand', 1), 272, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_sand', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.iron_sand', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrite_sand', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_sand', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.malachite_sand', 1), 169, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.garnierite_sand', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.nickel_sand', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_sand', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_sand', 1), 182, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.bentonite_sand', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.magnesite_sand', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.olivine_sand', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.beryllium_sand', 1), 845, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.emerald_sand', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.thorium_sand', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.grossular_sand', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.spessartine_sand', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrolusite_sand', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tantalite_sand', 1), 169, boost)
                    .duration(100)
                    .EUt(24)
                
            }
                //Aluminium
                    sandChance('aluminium', 'diamond', 350)
                //Stainless
                    sandChance('stainless', 'emerald', 450)
                //Titanium
                    sandChance('titanium', 'netherite', 500)
    //Andesite
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:andesite_sifting_type_bronze')
                .notConsumable(InputItem.of('exnihilosequentia:flint_mesh'))
                .itemInputs('exnihilosequentia:crushed_andesite')
                .chancedOutput(Item.of('gregicsifting:chunk.redstone_stone', 1), 1938, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ruby_stone', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_stone', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chromite_stone', 1), 161, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.almandine_stone', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrope_stone', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sapphire_stone', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.green_sapphire_stone', 1), 272, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.topaz_stone', 1), 600, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.blue_topaz_stone', 1), 400, 250)
                .duration(100)
                .EUt(24)
                  
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:andesite_sifting_type_steel')
                .notConsumable(InputItem.of('exnihilosequentia:iron_mesh'))
                .itemInputs('exnihilosequentia:crushed_andesite')
                .chancedOutput(Item.of('gregicsifting:chunk.redstone_stone', 1), 1938, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ruby_stone', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_stone', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chromite_stone', 1), 161, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.almandine_stone', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrope_stone', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sapphire_stone', 1), 816, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.green_sapphire_stone', 1), 272, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.topaz_stone', 1), 600, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.blue_topaz_stone', 1), 400, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.iron_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 323, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.malachite_stone', 1), 169, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bastnasite_stone', 1), 1014, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.monazite_stone', 1), 338, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.neodymium_stone', 1), 338, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.garnierite_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.nickel_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_stone', 1), 182, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bentonite_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.magnesite_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.olivine_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pitchblende_stone', 1), 845, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.uraninite_stone', 1), 676, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.graphite_stone', 1), 1014, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.diamond_stone', 1), 338, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 338, 250)
                .duration(100)
                .EUt(24)
             
        //Andesite-End
            function andesiteChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:andesite_sifting_type_${id}`)
                    .notConsumable(InputItem.of(`exnihilosequentia:${mesh}_mesh`))
                    .itemInputs('exnihilosequentia:crushed_andesite')
                    .chancedOutput(Item.of('gregicsifting:chunk.redstone_stone', 1), 1938, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.ruby_stone', 1), 646, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_stone', 1), 646, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chromite_stone', 1), 161, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.almandine_stone', 1), 816, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrope_stone', 1), 816, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.sapphire_stone', 1), 816, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.green_sapphire_stone', 1), 272, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.topaz_stone', 1), 600, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.blue_topaz_stone', 1), 400, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.iron_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrite_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 323, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.malachite_stone', 1), 169, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.bastnasite_stone', 1), 1014, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.monazite_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.neodymium_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.garnierite_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.nickel_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_stone', 1), 182, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.bentonite_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.magnesite_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.olivine_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pitchblende_stone', 1), 845, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.uraninite_stone', 1), 676, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.graphite_stone', 1), 1014, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.diamond_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.beryllium_stone', 1), 845, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.emerald_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.thorium_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.soapstone_stone', 1), 560, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.talc_stone', 1), 560, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.scheelite_stone', 1), 1014, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tungstate_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lithium_stone', 1), 338, boost)
                    .duration(100)
                    .EUt(24)
                
            }
                    //Aluminium
                        andesiteChance('aluminium', 'diamond', 350)
                    //Stainless
                        andesiteChance('stainless', 'emerald', 450)
                    //Titanium
                        andesiteChance('titanium', 'netherite', 500)
    //Granite
        //String
            event.recipes.gtceu.electric_sieve('gtceu:granite_sifting_type_string')
                .notConsumable(InputItem.of('exnihilosequentia:string_mesh'))
                .itemInputs('exnihilosequentia:crushed_granite')
                .chancedOutput(Item.of('gregicsifting:chunk.apatite_stone', 1), 1014, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tricalcium_phosphate_stone', 1), 676, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bauxite_stone', 1), 1530, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.aluminium_stone', 1), 765, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ilmenite_stone', 1), 255, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.magnetite_stone', 1), 2505, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.iron_stone', 1), 627, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.vanadium_magnetite_stone', 1), 627, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.gold_stone', 1), 418, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.quartzite_stone', 1), 994, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.barite_stone', 1), 553, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.certus_quartz_stone', 1), 663, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tetrahedrite_stone', 1), 1836, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 612, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.stibnite_stone', 1), 612, 250)
                .duration(100)
                .EUt(24);
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:granite_sifting_type_bronze')
                .notConsumable(InputItem.of('exnihilosequentia:flint_mesh'))
                .itemInputs('exnihilosequentia:crushed_granite')
                .chancedOutput(Item.of('gregicsifting:chunk.apatite_stone', 1), 1014, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tricalcium_phosphate_stone', 1), 676, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bauxite_stone', 1), 1530, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.aluminium_stone', 1), 765, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ilmenite_stone', 1), 255, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.magnetite_stone', 1), 2505, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.iron_stone', 1), 627, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.vanadium_magnetite_stone', 1), 627, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.gold_stone', 1), 418, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.quartzite_stone', 1), 994, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.barite_stone', 1), 553, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.certus_quartz_stone', 1), 663, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tetrahedrite_stone', 1), 1836, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 612, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.stibnite_stone', 1), 612, 250) 
                .chancedOutput(Item.of('gregicsifting:chunk.redstone_stone', 1), 1938, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ruby_stone', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_stone', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chromite_stone', 1), 161, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bornite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcocite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lazurite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sodalite_stone', 1), 390, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lapis_stone', 1), 683, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.calcite_stone', 1), 292, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.topaz_stone', 1), 600, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.blue_topaz_stone', 1), 400, 250)
                .duration(100)
                .EUt(24);
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:granite_sifting_type_steel')
                .notConsumable(InputItem.of('exnihilosequentia:iron_mesh'))
                .itemInputs('exnihilosequentia:crushed_granite')
                .chancedOutput(Item.of('gregicsifting:chunk.apatite_stone', 1), 1014, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tricalcium_phosphate_stone', 1), 676, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bauxite_stone', 1), 1530, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.aluminium_stone', 1), 765, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ilmenite_stone', 1), 255, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.magnetite_stone', 1), 2505, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.iron_stone', 1), 627, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.vanadium_magnetite_stone', 1), 627, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.gold_stone', 1), 418, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.quartzite_stone', 1), 994, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.barite_stone', 1), 553, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.certus_quartz_stone', 1), 663, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tetrahedrite_stone', 1), 1836, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 612, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.stibnite_stone', 1), 612, 250) 
                .chancedOutput(Item.of('gregicsifting:chunk.redstone_stone', 1), 1938, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ruby_stone', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_stone', 1), 646, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chromite_stone', 1), 161, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bornite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcocite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lazurite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sodalite_stone', 1), 390, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lapis_stone', 1), 683, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.calcite_stone', 1), 292, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.topaz_stone', 1), 600, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.blue_topaz_stone', 1), 400, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bastnasite_stone', 1), 1014, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.monazite_stone', 1), 338, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.neodymium_stone', 1), 338, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.garnierite_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.nickel_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_stone', 1), 182, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pitchblende_stone', 1), 845, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.uraninite_stone', 1), 676, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.kyanite_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.mica_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 364, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pollucite_stone', 1), 364, 250)
                .duration(100)
                .EUt(24);
        //Granite-End
            function graniteChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:granite_sifting_type_${id}`)
                    .notConsumable(InputItem.of(`exnihilosequentia:${mesh}_mesh`))
                    .itemInputs('exnihilosequentia:crushed_granite')
                    .chancedOutput(Item.of('gregicsifting:chunk.apatite_stone', 1), 1014, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tricalcium_phosphate_stone', 1), 676, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.bauxite_stone', 1), 1530, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.aluminium_stone', 1), 765, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.ilmenite_stone', 1), 255, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.magnetite_stone', 1), 2505, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.iron_stone', 1), 627, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.vanadium_magnetite_stone', 1), 627, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.gold_stone', 1), 418, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.quartzite_stone', 1), 994, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.barite_stone', 1), 553, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.certus_quartz_stone', 1), 663, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tetrahedrite_stone', 1), 1836, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 612, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.stibnite_stone', 1), 612, boost) 
                    .chancedOutput(Item.of('gregicsifting:chunk.redstone_stone', 1), 1938, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.ruby_stone', 1), 646, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_stone', 1), 646, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chromite_stone', 1), 161, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.bornite_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chalcocite_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lazurite_stone', 1), 585, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.sodalite_stone', 1), 390, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lapis_stone', 1), 683, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.calcite_stone', 1), 292, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.topaz_stone', 1), 600, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.blue_topaz_stone', 1), 400, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrite_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.bastnasite_stone', 1), 1014, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.monazite_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.neodymium_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.garnierite_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.nickel_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_stone', 1), 182, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pitchblende_stone', 1), 845, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.uraninite_stone', 1), 676, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.kyanite_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.mica_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 364, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pollucite_stone', 1), 364, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.graphite_stone', 1), 1014, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.diamond_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.wulfenite_stone', 1), 676, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.molybdenite_stone', 1), 676, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.powellite_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.soapstone_stone', 1), 560, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.talc_stone', 1), 560, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.scheelite_stone', 1), 1014, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tungstate_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lithium_stone', 1), 338, boost)
                    .duration(100)
                    .EUt(24);
            }
                    //Aluminium
                        graniteChance('aluminium', 'diamond', 350)
                    //Stainless
                        graniteChance('stainless', 'emerald', 450)
                    //Titanium
                        graniteChance('titanium', 'netherite', 500)
    //Diorite
        //String
            event.recipes.gtceu.electric_sieve('gtceu:diorite_sifting_type_string')
                .notConsumable(InputItem.of('exnihilosequentia:string_mesh'))
                .itemInputs('exnihilosequentia:crushed_diorite')
                .chancedOutput(Item.of('gregicsifting:chunk.bauxite_stone', 1), 1530, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.aluminium_stone', 1), 765, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ilmenite_stone', 1), 255, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 808, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.alunite_stone', 1), 195, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.quartzite_stone', 1), 994, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.barite_stone', 1), 553, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.certus_quartz_stone', 1), 663, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tin_stone', 1), 2422, 250)
                .duration(100)
                .EUt(24);
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:diorite_sifting_type_bronze')
                .notConsumable(InputItem.of('exnihilosequentia:flint_mesh'))
                .itemInputs('exnihilosequentia:crushed_diorite')
                .chancedOutput(Item.of('gregicsifting:chunk.bauxite_stone', 1), 1530, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.aluminium_stone', 1), 765, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ilmenite_stone', 1), 255, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 808, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.alunite_stone', 1), 195, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.quartzite_stone', 1), 994, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.barite_stone', 1), 553, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.certus_quartz_stone', 1), 663, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tin_stone', 1), 2422, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bornite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcocite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 323, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.galena_stone', 1), 1040, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lead_stone', 1), 520, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.silver_stone', 1), 520, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lazurite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sodalite_stone', 1), 390, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lapis_stone', 1), 683, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.calcite_stone', 1), 292, 250)
                .duration(100)
                .EUt(24);
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:diorite_sifting_type_steel')
                .notConsumable(InputItem.of('exnihilosequentia:iron_mesh'))
                .itemInputs('exnihilosequentia:crushed_diorite')
                .chancedOutput(Item.of('gregicsifting:chunk.bauxite_stone', 1), 1530, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.aluminium_stone', 1), 765, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.ilmenite_stone', 1), 255, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 808, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.alunite_stone', 1), 195, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.quartzite_stone', 1), 994, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.barite_stone', 1), 553, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.certus_quartz_stone', 1), 663, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tin_stone', 1), 2422, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bornite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chalcocite_stone', 1), 969, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 323, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.galena_stone', 1), 1040, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lead_stone', 1), 520, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.silver_stone', 1), 520, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lazurite_stone', 1), 585, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sodalite_stone', 1), 390, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lapis_stone', 1), 683, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.calcite_stone', 1), 292, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_stone', 1), 507, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.malachite_stone', 1), 169, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pitchblende_stone', 1), 845, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.uraninite_stone', 1), 676, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.kyanite_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.mica_stone', 1), 546, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 364, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pollucite_stone', 1), 364, 250)
                .duration(100)
                .EUt(24);
        //Diorite-End
            function dioriteChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:diorite_sifting_type_${id}`)
                    .notConsumable(InputItem.of(`exnihilosequentia:${mesh}_mesh`))
                    .itemInputs('exnihilosequentia:crushed_diorite')
                    .chancedOutput(Item.of('gregicsifting:chunk.bauxite_stone', 1), 1530, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.aluminium_stone', 1), 765, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.ilmenite_stone', 1), 255, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_stone', 1), 585, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 808, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 585, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.alunite_stone', 1), 195, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.quartzite_stone', 1), 994, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.barite_stone', 1), 553, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.certus_quartz_stone', 1), 663, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tin_stone', 1), 2422, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.bornite_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chalcocite_stone', 1), 969, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.copper_stone', 1), 323, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.galena_stone', 1), 1040, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lead_stone', 1), 520, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.silver_stone', 1), 520, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lazurite_stone', 1), 585, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.sodalite_stone', 1), 390, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lapis_stone', 1), 683, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.calcite_stone', 1), 292, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_stone', 1), 507, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.malachite_stone', 1), 169, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pitchblende_stone', 1), 845, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.uraninite_stone', 1), 676, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.kyanite_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.mica_stone', 1), 546, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cassiterite_stone', 1), 364, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pollucite_stone', 1), 364, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.graphite_stone', 1), 1014, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.diamond_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.coal_stone', 1), 338, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.soapstone_stone', 1), 560, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.talc_stone', 1), 560, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_stone', 1), 560, boost)
                    .duration(100)
                    .EUt(24);

            }
                    //Aluminium
                        dioriteChance('aluminium', 'diamond', 350)
                    //Stainless
                        dioriteChance('stainless', 'emerald', 450)
                    //Titanium
                        dioriteChance('titanium', 'netherite', 500)
    //Netherrack
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:netherrack_sifting_type_bronze')
                .notConsumable(InputItem.of('exnihilosequentia:flint_mesh'))
                .itemInputs('exnihilosequentia:crushed_netherrack')
                .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_nether', 1), 432, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.iron_nether', 1), 357, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.iron_nether', 1), 432, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrite_nether', 1), 544, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrite_nether', 1), 432, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.copper_nether', 1), 144, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.copper_nether', 1), 312, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_nether', 1), 324, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.malachite_nether', 1), 108, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.magnetite_nether', 1), 1428, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.vanadium_magnetite_nether', 1), 357, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.gold_nether', 1), 238, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.nether_quartz_nether', 1), 3240, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sulfur_nether', 1), 1632, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sphalerite_nether', 1), 544, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tetrahedrite_nether', 1), 936, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.stibnite_nether', 1), 312, 250)
                .duration(100)
                .EUt(24);
        //Netherrack-End
            function netherChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:netherrack_sifting_type_${id}`)
                    .notConsumable(InputItem.of(`exnihilosequentia:${mesh}_mesh`))
                    .itemInputs('exnihilosequentia:crushed_netherrack')
                    .chancedOutput(Item.of('gregicsifting:chunk.chalcopyrite_nether', 1), 432, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.iron_nether', 1), 357, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.iron_nether', 1), 432, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrite_nether', 1), 544, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrite_nether', 1), 432, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.copper_nether', 1), 144, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.copper_nether', 1), 312, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.yellow_limonite_nether', 1), 324, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.malachite_nether', 1), 108, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.magnetite_nether', 1), 1428, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.vanadium_magnetite_nether', 1), 357, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.gold_nether', 1), 238, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.nether_quartz_nether', 1), 3240, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.sulfur_nether', 1), 1632, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.sphalerite_nether', 1), 544, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tetrahedrite_nether', 1), 936, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.stibnite_nether', 1), 312, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.garnierite_nether', 1), 189, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.nickel_nether', 1), 189, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_nether', 1), 189, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_nether', 1), 63, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.redstone_nether', 1), 864, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.ruby_nether', 1), 288, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cinnabar_nether', 1), 288, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chromite_nether', 1), 72, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.electrotine_nether', 1), 72, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.topaz_nether', 1), 294, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.blue_topaz_nether', 1), 196, boost)
                    .duration(100)
                    .EUt(24);

            }
                    //Aluminium
                        netherChance('aluminium', 'diamond', 350)
                    //Stainless
                        netherChance('stainless', 'emerald', 450)
                    //Titanium
                        netherChance('titanium', 'netherite', 500)
    //Endstone
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:endstone_sifting_type_bronze')
                .notConsumable(InputItem.of('exnihilosequentia:flint_mesh'))
                .itemInputs('exnihilosequentia:crushed_end_stone')
                .chancedOutput(Item.of('gregicsifting:chunk.beryllium_end', 1), 405, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.emerald_end', 1), 243, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.thorium_end', 1), 162, 250)
                .duration(100)
                .EUt(24);
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:endstone_sifting_type_steel')
                .notConsumable(InputItem.of('exnihilosequentia:iron_mesh'))
                .itemInputs('exnihilosequentia:crushed_end_stone')
                .chancedOutput(Item.of('gregicsifting:chunk.beryllium_end', 1), 405, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.emerald_end', 1), 243, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.thorium_end', 1), 162, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.grossular_end', 1), 192, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.spessartine_end', 1), 192, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pyrolusite_end', 1), 192, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tantalite_end', 1), 64, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.wulfenite_end', 1), 256, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.molybdenite_end', 1), 256, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.powellite_end', 1), 128, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.garnierite_end', 1), 189, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.nickel_end', 1), 189, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_end', 1), 189, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_end', 1), 63, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.bentonite_end', 1), 192, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.magnesite_end', 1), 192, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.olivine_end', 1), 192, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.chromite_end', 1), 640, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.sheldonite_end', 1), 288, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.palladium_end', 1), 224, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.scheelite_end', 1), 384, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.tungstate_end', 1), 128, 250)
                .chancedOutput(Item.of('gregicsifting:chunk.lithium_end', 1), 128, 250)
                .duration(100)
                .EUt(24);
        //Endstone-End
            function endChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:endstone_sifting_type_${id}`)
                    .notConsumable(InputItem.of(`exnihilosequentia:${mesh}_mesh`))
                    .itemInputs('exnihilosequentia:crushed_end_stone')
                    .chancedOutput(Item.of('gregicsifting:chunk.beryllium_end', 1), 405, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.emerald_end', 1), 243, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.thorium_end', 1), 162, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.grossular_end', 1), 192, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.spessartine_end', 1), 192, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pyrolusite_end', 1), 192, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tantalite_end', 1), 64, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.wulfenite_end', 1), 256, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.molybdenite_end', 1), 256, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.powellite_end', 1), 128, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.garnierite_end', 1), 189, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.nickel_end', 1), 189, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.cobaltite_end', 1), 189, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.pentlandite_end', 1), 63, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.bentonite_end', 1), 192, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.magnesite_end', 1), 192, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.olivine_end', 1), 192, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.chromite_end', 1), 640, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.sheldonite_end', 1), 288, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.palladium_end', 1), 224, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.scheelite_end', 1), 384, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.tungstate_end', 1), 128, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lithium_end', 1), 128, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.naquadah_end', 1), 3600, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lazurite_end', 1), 216, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.sodalite_end', 1), 144, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.lapis_end', 1), 252, boost)
                    .chancedOutput(Item.of('gregicsifting:chunk.calcite_end', 1), 108, boost)
                    .duration(100)
                    .EUt(24);

            }
                    //Aluminium
                        endChance('aluminium', 'diamond', 350)
                    //Stainless
                        endChance('stainless', 'emerald', 450)
                    //Titanium
                        endChance('titanium', 'netherite', 500)
})
