ServerEvents.recipes(event => {
    //Gravel
                //String
                event.recipes.gtceu.electric_sieve("gtceu:gravel_sifting_type_string")
                .chance(0)
                .itemInputs('exnihilosequentia:string_mesh')
                .chance(1)
                .itemInputs('minecraft:gravel')
                .chancedOutput('gregicsifting:chunk.coal_stone', 1920, 250)
                .chancedOutput('gregicsifting:chunk.coal_stone', 950, 250)
                .chancedOutput('gregicsifting:chunk.trona_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.salt_stone', 925, 250)
                .chancedOutput('gregicsifting:chunk.rock_salt_stone', 833, 250)
                .chancedOutput('gregicsifting:chunk.lepidolite_stone', 357, 250)
                .chancedOutput('gregicsifting:chunk.spodumene_stone', 238, 250)
                .chancedOutput('gregicsifting:chunk.tin_stone', 2422, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 808, 250)
                .chancedOutput('gregicsifting:chunk.basaltic_mineral_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.granitic_mineral_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.fullers_earth_stone', 364, 250)
                .chancedOutput('gregicsifting:chunk.gypsum_stone', 364, 250)
                .duration(100)
                .EUt(24)
            
        //bronze
             event.recipes.gtceu.electric_sieve("gtceu:gravel_sifting_type_bronze")
                .chance(0)
                .itemInputs('exnihilosequentia:flint_mesh')
                .chance(1)
                .itemInputs('minecraft:gravel')
                .chancedOutput('gregicsifting:chunk.coal_stone', 1920, 250)
                .chancedOutput('gregicsifting:chunk.coal_stone', 950, 250)
                .chancedOutput('gregicsifting:chunk.trona_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.salt_stone', 925, 250)
                .chancedOutput('gregicsifting:chunk.rock_salt_stone', 833, 250)
                .chancedOutput('gregicsifting:chunk.lepidolite_stone', 357, 250)
                .chancedOutput('gregicsifting:chunk.spodumene_stone', 238, 250)
                .chancedOutput('gregicsifting:chunk.tin_stone', 2422, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 808, 250)
                .chancedOutput('gregicsifting:chunk.basaltic_mineral_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.granitic_mineral_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.fullers_earth_stone', 364, 250)
                .chancedOutput('gregicsifting:chunk.gypsum_stone', 364, 250)
                .chancedOutput('gregicsifting:chunk.galena_stone', 1040, 250)
                .chancedOutput('gregicsifting:chunk.lead_stone', 520, 250)
                .chancedOutput('gregicsifting:chunk.silver_stone', 520, 250)
                .chancedOutput('gregicsifting:chunk.zeolite_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.glauconite_sand_stone', 338, 250)
                .chancedOutput('gregicsifting:chunk.oilsands_stone', 2250, 250)
                .chancedOutput('gregicsifting:chunk.garnet_sand_stone', 432, 250)
                .chancedOutput('gregicsifting:chunk.asbestos_stone', 432, 250)
                .chancedOutput('gregicsifting:chunk.diatomite_stone', 144, 250)
                .duration(100)
                .EUt(24)
            
        //Gravel-End
            function gravelChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:gravel_sifting_type_${id}`)
                    .chance(0)
                    .itemInputs(`exnihilosequentia:${mesh}_mesh`)
                    .chance(1)
                    .itemInputs('minecraft:gravel')
                    .chancedOutput('gregicsifting:chunk.coal_stone', 1920, boost)
                    .chancedOutput('gregicsifting:chunk.coal_stone', 950, boost)
                    .chancedOutput('gregicsifting:chunk.trona_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.salt_stone', 925, boost)
                    .chancedOutput('gregicsifting:chunk.rock_salt_stone', 833, boost)
                    .chancedOutput('gregicsifting:chunk.lepidolite_stone', 357, boost)
                    .chancedOutput('gregicsifting:chunk.spodumene_stone', 238, boost)
                    .chancedOutput('gregicsifting:chunk.tin_stone', 2422, boost)
                    .chancedOutput('gregicsifting:chunk.cassiterite_stone', 808, boost)
                    .chancedOutput('gregicsifting:chunk.basaltic_mineral_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.granitic_mineral_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.fullers_earth_stone', 364, boost)
                    .chancedOutput('gregicsifting:chunk.gypsum_stone', 364, boost)
                    .chancedOutput('gregicsifting:chunk.galena_stone', 1040, boost)
                    .chancedOutput('gregicsifting:chunk.lead_stone', 520, boost)
                    .chancedOutput('gregicsifting:chunk.silver_stone', 520, boost)
                    .chancedOutput('gregicsifting:chunk.zeolite_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.glauconite_sand_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.oilsands_stone', 2250, boost)
                    .chancedOutput('gregicsifting:chunk.garnet_sand_stone', 432, boost)
                    .chancedOutput('gregicsifting:chunk.asbestos_stone', 432, boost)
                    .chancedOutput('gregicsifting:chunk.diatomite_stone', 144, boost)
                    .chancedOutput('gregicsifting:chunk.platinum_stone', 760, boost)
                    .chancedOutput('gregicsifting:chunk.palladium_stone', 591, boost)
                    .duration(100)
                    .EUt(24)     
            }
                //Steel
                    gravelChance('steel', 'iron', 250)
                //Aluminium
                    gravelChance('aluminium', 'diamond', 350)
                //Stainless
                    gravelChance('stainless', 'emerald', 450)
                //Titanium
                    gravelChance('titanium', 'netherite', 500)                
    //Sand
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:sand_sifting_type_bronze')
                .chance(0)
                .itemInputs('exnihilosequentia:flint_mesh')
                .chance(1)
                .itemInputs('minecraft:sand')
                .chancedOutput('gregicsifting:chunk.copper_sand', 612, 250)
                .chancedOutput('gregicsifting:chunk.redstone_sand', 1938, 250)
                .chancedOutput('gregicsifting:chunk.cinnabar_sand', 646, 250)
                .chancedOutput('gregicsifting:chunk.chromite_sand', 161, 250)
                .chancedOutput('gregicsifting:chunk.pyrope_sand', 816, 250)
                .chancedOutput('gregicsifting:chunk.sapphire_sand', 816, 250)
                .chancedOutput('gregicsifting:chunk.green_sapphire_sand', 272, 250)
                .duration(100)
                .EUt(24)
            
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:sand_sifting_type_steel')
                .chance(0)
                .itemInputs('exnihilosequentia:iron_mesh')
                .chance(1)
                .itemInputs('minecraft:sand')
                .chancedOutput('gregicsifting:chunk.copper_sand', 612, 250)
                .chancedOutput('gregicsifting:chunk.redstone_sand', 1938, 250)
                .chancedOutput('gregicsifting:chunk.cinnabar_sand', 646, 250)
                .chancedOutput('gregicsifting:chunk.chromite_sand', 161, 250)
                .chancedOutput('gregicsifting:chunk.pyrope_sand', 816, 250)
                .chancedOutput('gregicsifting:chunk.sapphire_sand', 816, 250)
                .chancedOutput('gregicsifting:chunk.green_sapphire_sand', 272, 250)
                .chancedOutput('gregicsifting:chunk.chalcopyrite_sand', 969, 250)
                .chancedOutput('gregicsifting:chunk.iron_sand', 969, 250)
                .chancedOutput('gregicsifting:chunk.pyrite_sand', 969, 250)
                .chancedOutput('gregicsifting:chunk.yellow_limonite_sand', 507, 250)
                .chancedOutput('gregicsifting:chunk.malachite_sand', 169, 250)
                .chancedOutput('gregicsifting:chunk.garnierite_sand', 546, 250)
                .chancedOutput('gregicsifting:chunk.nickel_sand', 546, 250)
                .chancedOutput('gregicsifting:chunk.cobaltite_sand', 546, 250)
                .chancedOutput('gregicsifting:chunk.pentlandite_sand', 182, 250)
                .chancedOutput('gregicsifting:chunk.bentonite_sand', 507, 250)
                .chancedOutput('gregicsifting:chunk.magnesite_sand', 507, 250)
                .chancedOutput('gregicsifting:chunk.olivine_sand', 507, 250)
                .duration(100)
                .EUt(24)
            
        //Sand-End
            function sandChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:sand_sifting_type_${id}`)
                    .chance(0)
                    .itemInputs(`exnihilosequentia:${mesh}_mesh`)
                    .chance(1)
                    .itemInputs('minecraft:sand')
                    .chancedOutput('gregicsifting:chunk.copper_sand', 612, boost)
                    .chancedOutput('gregicsifting:chunk.redstone_sand', 1938, boost)
                    .chancedOutput('gregicsifting:chunk.cinnabar_sand', 646, boost)
                    .chancedOutput('gregicsifting:chunk.chromite_sand', 161, boost)
                    .chancedOutput('gregicsifting:chunk.pyrope_sand', 816, boost)
                    .chancedOutput('gregicsifting:chunk.sapphire_sand', 816, boost)
                    .chancedOutput('gregicsifting:chunk.green_sapphire_sand', 272, boost)
                    .chancedOutput('gregicsifting:chunk.chalcopyrite_sand', 969, boost)
                    .chancedOutput('gregicsifting:chunk.iron_sand', 969, boost)
                    .chancedOutput('gregicsifting:chunk.pyrite_sand', 969, boost)
                    .chancedOutput('gregicsifting:chunk.yellow_limonite_sand', 507, boost)
                    .chancedOutput('gregicsifting:chunk.malachite_sand', 169, boost)
                    .chancedOutput('gregicsifting:chunk.garnierite_sand', 546, boost)
                    .chancedOutput('gregicsifting:chunk.nickel_sand', 546, boost)
                    .chancedOutput('gregicsifting:chunk.cobaltite_sand', 546, boost)
                    .chancedOutput('gregicsifting:chunk.pentlandite_sand', 182, boost)
                    .chancedOutput('gregicsifting:chunk.bentonite_sand', 507, boost)
                    .chancedOutput('gregicsifting:chunk.magnesite_sand', 507, boost)
                    .chancedOutput('gregicsifting:chunk.olivine_sand', 507, boost)
                    .chancedOutput('gregicsifting:chunk.beryllium_sand', 845, boost)
                    .chancedOutput('gregicsifting:chunk.emerald_sand', 507, boost)
                    .chancedOutput('gregicsifting:chunk.thorium_sand', 338, boost)
                    .chancedOutput('gregicsifting:chunk.grossular_sand', 507, boost)
                    .chancedOutput('gregicsifting:chunk.spessartine_sand', 507, boost)
                    .chancedOutput('gregicsifting:chunk.pyrolusite_sand', 507, boost)
                    .chancedOutput('gregicsifting:chunk.tantalite_sand', 169, boost)
                    .duration(100)
                    .EUt(24)
                
            }
                //Aluminium
                    sandChance('aluminium', 'diamond', 350)
                //Stainless
                    sandChance('stainless', 'emerald', 450)
                //Titanium
                    sandChance('titanium', 'netherite', 500)
    //Andesite
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:andesite_sifting_type_bronze')
                .chance(0)
                .itemInputs('exnihilosequentia:flint_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_andesite')
                .chancedOutput('gregicsifting:chunk.redstone_stone', 1938, 250)
                .chancedOutput('gregicsifting:chunk.ruby_stone', 646, 250)
                .chancedOutput('gregicsifting:chunk.cinnabar_stone', 646, 250)
                .chancedOutput('gregicsifting:chunk.chromite_stone', 161, 250)
                .chancedOutput('gregicsifting:chunk.almandine_stone', 816, 250)
                .chancedOutput('gregicsifting:chunk.pyrope_stone', 816, 250)
                .chancedOutput('gregicsifting:chunk.sapphire_stone', 816, 250)
                .chancedOutput('gregicsifting:chunk.green_sapphire_stone', 272, 250)
                .chancedOutput('gregicsifting:chunk.topaz_stone', 600, 250)
                .chancedOutput('gregicsifting:chunk.blue_topaz_stone', 400, 250)
                .duration(100)
                .EUt(24)
                  
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:andesite_sifting_type_steel')
                .chance(0)
                .itemInputs('exnihilosequentia:iron_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_andesite')
                .chancedOutput('gregicsifting:chunk.redstone_stone', 1938, 250)
                .chancedOutput('gregicsifting:chunk.ruby_stone', 646, 250)
                .chancedOutput('gregicsifting:chunk.cinnabar_stone', 646, 250)
                .chancedOutput('gregicsifting:chunk.chromite_stone', 161, 250)
                .chancedOutput('gregicsifting:chunk.almandine_stone', 816, 250)
                .chancedOutput('gregicsifting:chunk.pyrope_stone', 816, 250)
                .chancedOutput('gregicsifting:chunk.sapphire_stone', 816, 250)
                .chancedOutput('gregicsifting:chunk.green_sapphire_stone', 272, 250)
                .chancedOutput('gregicsifting:chunk.topaz_stone', 600, 250)
                .chancedOutput('gregicsifting:chunk.blue_topaz_stone', 400, 250)
                .chancedOutput('gregicsifting:chunk.chalcopyrite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.iron_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.pyrite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.copper_stone', 323, 250)
                .chancedOutput('gregicsifting:chunk.yellow_limonite_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.malachite_stone', 169, 250)
                .chancedOutput('gregicsifting:chunk.bastnasite_stone', 1014, 250)
                .chancedOutput('gregicsifting:chunk.monazite_stone', 338, 250)
                .chancedOutput('gregicsifting:chunk.neodymium_stone', 338, 250)
                .chancedOutput('gregicsifting:chunk.garnierite_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.nickel_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.cobaltite_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.pentlandite_stone', 182, 250)
                .chancedOutput('gregicsifting:chunk.bentonite_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.magnesite_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.olivine_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.pitchblende_stone', 845, 250)
                .chancedOutput('gregicsifting:chunk.uraninite_stone', 676, 250)
                .chancedOutput('gregicsifting:chunk.graphite_stone', 1014, 250)
                .chancedOutput('gregicsifting:chunk.diamond_stone', 338, 250)
                .chancedOutput('gregicsifting:chunk.coal_stone', 338, 250)
                .duration(100)
                .EUt(24)
             
        //Andesite-End
            function andesiteChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:andesite_sifting_type_${id}`)
                    .chance(0)
                    .itemInputs(`exnihilosequentia:${mesh}_mesh`)
                    .chance(1)
                    .itemInputs('exnihilosequentia:crushed_andesite')
                    .chancedOutput('gregicsifting:chunk.redstone_stone', 1938, boost)
                    .chancedOutput('gregicsifting:chunk.ruby_stone', 646, boost)
                    .chancedOutput('gregicsifting:chunk.cinnabar_stone', 646, boost)
                    .chancedOutput('gregicsifting:chunk.chromite_stone', 161, boost)
                    .chancedOutput('gregicsifting:chunk.almandine_stone', 816, boost)
                    .chancedOutput('gregicsifting:chunk.pyrope_stone', 816, boost)
                    .chancedOutput('gregicsifting:chunk.sapphire_stone', 816, boost)
                    .chancedOutput('gregicsifting:chunk.green_sapphire_stone', 272, boost)
                    .chancedOutput('gregicsifting:chunk.topaz_stone', 600, boost)
                    .chancedOutput('gregicsifting:chunk.blue_topaz_stone', 400, boost)
                    .chancedOutput('gregicsifting:chunk.chalcopyrite_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.iron_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.pyrite_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.copper_stone', 323, boost)
                    .chancedOutput('gregicsifting:chunk.yellow_limonite_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.malachite_stone', 169, boost)
                    .chancedOutput('gregicsifting:chunk.bastnasite_stone', 1014, boost)
                    .chancedOutput('gregicsifting:chunk.monazite_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.neodymium_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.garnierite_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.nickel_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.cobaltite_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.pentlandite_stone', 182, boost)
                    .chancedOutput('gregicsifting:chunk.bentonite_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.magnesite_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.olivine_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.pitchblende_stone', 845, boost)
                    .chancedOutput('gregicsifting:chunk.uraninite_stone', 676, boost)
                    .chancedOutput('gregicsifting:chunk.graphite_stone', 1014, boost)
                    .chancedOutput('gregicsifting:chunk.diamond_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.coal_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.beryllium_stone', 845, boost)
                    .chancedOutput('gregicsifting:chunk.emerald_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.thorium_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.soapstone_stone', 560, boost)
                    .chancedOutput('gregicsifting:chunk.talc_stone', 560, boost)
                    .chancedOutput('gregicsifting:chunk.scheelite_stone', 1014, boost)
                    .chancedOutput('gregicsifting:chunk.tungstate_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.lithium_stone', 338, boost)
                    .duration(100)
                    .EUt(24)
                
            }
                    //Aluminium
                        andesiteChance('aluminium', 'diamond', 350)
                    //Stainless
                        andesiteChance('stainless', 'emerald', 450)
                    //Titanium
                        andesiteChance('titanium', 'netherite', 500)
    //Granite
        //String
            event.recipes.gtceu.electric_sieve('gtceu:granite_sifting_type_string')
                .chance(0)
                .itemInputs('exnihilosequentia:string_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_granite')
                .chancedOutput('gregicsifting:chunk.apatite_stone', 1014, 250)
                .chancedOutput('gregicsifting:chunk.tricalcium_phosphate_stone', 676, 250)
                .chancedOutput('gregicsifting:chunk.bauxite_stone', 1530, 250)
                .chancedOutput('gregicsifting:chunk.aluminium_stone', 765, 250)
                .chancedOutput('gregicsifting:chunk.ilmenite_stone', 255, 250)
                .chancedOutput('gregicsifting:chunk.magnetite_stone', 2505, 250)
                .chancedOutput('gregicsifting:chunk.iron_stone', 627, 250)
                .chancedOutput('gregicsifting:chunk.vanadium_magnetite_stone', 627, 250)
                .chancedOutput('gregicsifting:chunk.gold_stone', 418, 250)
                .chancedOutput('gregicsifting:chunk.quartzite_stone', 994, 250)
                .chancedOutput('gregicsifting:chunk.barite_stone', 553, 250)
                .chancedOutput('gregicsifting:chunk.certus_quartz_stone', 663, 250)
                .chancedOutput('gregicsifting:chunk.tetrahedrite_stone', 1836, 250)
                .chancedOutput('gregicsifting:chunk.copper_stone', 612, 250)
                .chancedOutput('gregicsifting:chunk.stibnite_stone', 612, 250)
                .duration(100)
                .EUt(24);
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:granite_sifting_type_bronze')
                .chance(0)
                .itemInputs('exnihilosequentia:flint_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_granite')
                .chancedOutput('gregicsifting:chunk.apatite_stone', 1014, 250)
                .chancedOutput('gregicsifting:chunk.tricalcium_phosphate_stone', 676, 250)
                .chancedOutput('gregicsifting:chunk.bauxite_stone', 1530, 250)
                .chancedOutput('gregicsifting:chunk.aluminium_stone', 765, 250)
                .chancedOutput('gregicsifting:chunk.ilmenite_stone', 255, 250)
                .chancedOutput('gregicsifting:chunk.magnetite_stone', 2505, 250)
                .chancedOutput('gregicsifting:chunk.iron_stone', 627, 250)
                .chancedOutput('gregicsifting:chunk.vanadium_magnetite_stone', 627, 250)
                .chancedOutput('gregicsifting:chunk.gold_stone', 418, 250)
                .chancedOutput('gregicsifting:chunk.quartzite_stone', 994, 250)
                .chancedOutput('gregicsifting:chunk.barite_stone', 553, 250)
                .chancedOutput('gregicsifting:chunk.certus_quartz_stone', 663, 250)
                .chancedOutput('gregicsifting:chunk.tetrahedrite_stone', 1836, 250)
                .chancedOutput('gregicsifting:chunk.copper_stone', 612, 250)
                .chancedOutput('gregicsifting:chunk.stibnite_stone', 612, 250) 
                .chancedOutput('gregicsifting:chunk.redstone_stone', 1938, 250)
                .chancedOutput('gregicsifting:chunk.ruby_stone', 646, 250)
                .chancedOutput('gregicsifting:chunk.cinnabar_stone', 646, 250)
                .chancedOutput('gregicsifting:chunk.chromite_stone', 161, 250)
                .chancedOutput('gregicsifting:chunk.bornite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.chalcocite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.lazurite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.sodalite_stone', 390, 250)
                .chancedOutput('gregicsifting:chunk.lapis_stone', 683, 250)
                .chancedOutput('gregicsifting:chunk.calcite_stone', 292, 250)
                .chancedOutput('gregicsifting:chunk.topaz_stone', 600, 250)
                .chancedOutput('gregicsifting:chunk.blue_topaz_stone', 400, 250)
                .duration(100)
                .EUt(24);
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:granite_sifting_type_steel')
                .chance(0)
                .itemInputs('exnihilosequentia:iron_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_granite')
                .chancedOutput('gregicsifting:chunk.apatite_stone', 1014, 250)
                .chancedOutput('gregicsifting:chunk.tricalcium_phosphate_stone', 676, 250)
                .chancedOutput('gregicsifting:chunk.bauxite_stone', 1530, 250)
                .chancedOutput('gregicsifting:chunk.aluminium_stone', 765, 250)
                .chancedOutput('gregicsifting:chunk.ilmenite_stone', 255, 250)
                .chancedOutput('gregicsifting:chunk.magnetite_stone', 2505, 250)
                .chancedOutput('gregicsifting:chunk.iron_stone', 627, 250)
                .chancedOutput('gregicsifting:chunk.vanadium_magnetite_stone', 627, 250)
                .chancedOutput('gregicsifting:chunk.gold_stone', 418, 250)
                .chancedOutput('gregicsifting:chunk.quartzite_stone', 994, 250)
                .chancedOutput('gregicsifting:chunk.barite_stone', 553, 250)
                .chancedOutput('gregicsifting:chunk.certus_quartz_stone', 663, 250)
                .chancedOutput('gregicsifting:chunk.tetrahedrite_stone', 1836, 250)
                .chancedOutput('gregicsifting:chunk.copper_stone', 612, 250)
                .chancedOutput('gregicsifting:chunk.stibnite_stone', 612, 250) 
                .chancedOutput('gregicsifting:chunk.redstone_stone', 1938, 250)
                .chancedOutput('gregicsifting:chunk.ruby_stone', 646, 250)
                .chancedOutput('gregicsifting:chunk.cinnabar_stone', 646, 250)
                .chancedOutput('gregicsifting:chunk.chromite_stone', 161, 250)
                .chancedOutput('gregicsifting:chunk.bornite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.chalcocite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.lazurite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.sodalite_stone', 390, 250)
                .chancedOutput('gregicsifting:chunk.lapis_stone', 683, 250)
                .chancedOutput('gregicsifting:chunk.calcite_stone', 292, 250)
                .chancedOutput('gregicsifting:chunk.topaz_stone', 600, 250)
                .chancedOutput('gregicsifting:chunk.blue_topaz_stone', 400, 250)
                .chancedOutput('gregicsifting:chunk.chalcopyrite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.pyrite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.yellow_limonite_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.bastnasite_stone', 1014, 250)
                .chancedOutput('gregicsifting:chunk.monazite_stone', 338, 250)
                .chancedOutput('gregicsifting:chunk.neodymium_stone', 338, 250)
                .chancedOutput('gregicsifting:chunk.garnierite_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.nickel_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.cobaltite_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.pentlandite_stone', 182, 250)
                .chancedOutput('gregicsifting:chunk.pitchblende_stone', 845, 250)
                .chancedOutput('gregicsifting:chunk.uraninite_stone', 676, 250)
                .chancedOutput('gregicsifting:chunk.kyanite_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.mica_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 364, 250)
                .chancedOutput('gregicsifting:chunk.pollucite_stone', 364, 250)
                .duration(100)
                .EUt(24);
        //Granite-End
            function graniteChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:granite_sifting_type_${id}`)
                    .chance(0)
                    .itemInputs(`exnihilosequentia:${mesh}_mesh`)
                    .chance(1)
                    .itemInputs('exnihilosequentia:crushed_granite')
                    .chancedOutput('gregicsifting:chunk.apatite_stone', 1014, boost)
                    .chancedOutput('gregicsifting:chunk.tricalcium_phosphate_stone', 676, boost)
                    .chancedOutput('gregicsifting:chunk.bauxite_stone', 1530, boost)
                    .chancedOutput('gregicsifting:chunk.aluminium_stone', 765, boost)
                    .chancedOutput('gregicsifting:chunk.ilmenite_stone', 255, boost)
                    .chancedOutput('gregicsifting:chunk.magnetite_stone', 2505, boost)
                    .chancedOutput('gregicsifting:chunk.iron_stone', 627, boost)
                    .chancedOutput('gregicsifting:chunk.vanadium_magnetite_stone', 627, boost)
                    .chancedOutput('gregicsifting:chunk.gold_stone', 418, boost)
                    .chancedOutput('gregicsifting:chunk.quartzite_stone', 994, boost)
                    .chancedOutput('gregicsifting:chunk.barite_stone', 553, boost)
                    .chancedOutput('gregicsifting:chunk.certus_quartz_stone', 663, boost)
                    .chancedOutput('gregicsifting:chunk.tetrahedrite_stone', 1836, boost)
                    .chancedOutput('gregicsifting:chunk.copper_stone', 612, boost)
                    .chancedOutput('gregicsifting:chunk.stibnite_stone', 612, boost) 
                    .chancedOutput('gregicsifting:chunk.redstone_stone', 1938, boost)
                    .chancedOutput('gregicsifting:chunk.ruby_stone', 646, boost)
                    .chancedOutput('gregicsifting:chunk.cinnabar_stone', 646, boost)
                    .chancedOutput('gregicsifting:chunk.chromite_stone', 161, boost)
                    .chancedOutput('gregicsifting:chunk.bornite_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.chalcocite_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.lazurite_stone', 585, boost)
                    .chancedOutput('gregicsifting:chunk.sodalite_stone', 390, boost)
                    .chancedOutput('gregicsifting:chunk.lapis_stone', 683, boost)
                    .chancedOutput('gregicsifting:chunk.calcite_stone', 292, boost)
                    .chancedOutput('gregicsifting:chunk.topaz_stone', 600, boost)
                    .chancedOutput('gregicsifting:chunk.blue_topaz_stone', 400, boost)
                    .chancedOutput('gregicsifting:chunk.chalcopyrite_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.pyrite_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.yellow_limonite_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.bastnasite_stone', 1014, boost)
                    .chancedOutput('gregicsifting:chunk.monazite_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.neodymium_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.garnierite_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.nickel_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.cobaltite_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.pentlandite_stone', 182, boost)
                    .chancedOutput('gregicsifting:chunk.pitchblende_stone', 845, boost)
                    .chancedOutput('gregicsifting:chunk.uraninite_stone', 676, boost)
                    .chancedOutput('gregicsifting:chunk.kyanite_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.mica_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.cassiterite_stone', 364, boost)
                    .chancedOutput('gregicsifting:chunk.pollucite_stone', 364, boost)
                    .chancedOutput('gregicsifting:chunk.graphite_stone', 1014, boost)
                    .chancedOutput('gregicsifting:chunk.diamond_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.coal_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.wulfenite_stone', 676, boost)
                    .chancedOutput('gregicsifting:chunk.molybdenite_stone', 676, boost)
                    .chancedOutput('gregicsifting:chunk.powellite_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.soapstone_stone', 560, boost)
                    .chancedOutput('gregicsifting:chunk.talc_stone', 560, boost)
                    .chancedOutput('gregicsifting:chunk.scheelite_stone', 1014, boost)
                    .chancedOutput('gregicsifting:chunk.tungstate_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.lithium_stone', 338, boost)
                    .duration(100)
                    .EUt(24);
            }
                    //Aluminium
                        graniteChance('aluminium', 'diamond', 350)
                    //Stainless
                        graniteChance('stainless', 'emerald', 450)
                    //Titanium
                        graniteChance('titanium', 'netherrite', 500)
    //Diorite
        //String
            event.recipes.gtceu.electric_sieve('gtceu:diorite_sifting_type_string')
                .chance(0)
                .itemInputs('exnihilosequentia:string_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_diorite')
                .chancedOutput('gregicsifting:chunk.bauxite_stone', 1530, 250)
                .chancedOutput('gregicsifting:chunk.aluminium_stone', 765, 250)
                .chancedOutput('gregicsifting:chunk.ilmenite_stone', 255, 250)
                .chancedOutput('gregicsifting:chunk.chalcopyrite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 808, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.alunite_stone', 195, 250)
                .chancedOutput('gregicsifting:chunk.quartzite_stone', 994, 250)
                .chancedOutput('gregicsifting:chunk.barite_stone', 553, 250)
                .chancedOutput('gregicsifting:chunk.certus_quartz_stone', 663, 250)
                .chancedOutput('gregicsifting:chunk.tin_stone', 2422, 250)
                .duration(100)
                .EUt(24);
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:diorite_sifting_type_bronze')
                .chance(0)
                .itemInputs('exnihilosequentia:flint_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_diorite')
                .chancedOutput('gregicsifting:chunk.bauxite_stone', 1530, 250)
                .chancedOutput('gregicsifting:chunk.aluminium_stone', 765, 250)
                .chancedOutput('gregicsifting:chunk.ilmenite_stone', 255, 250)
                .chancedOutput('gregicsifting:chunk.chalcopyrite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 808, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.alunite_stone', 195, 250)
                .chancedOutput('gregicsifting:chunk.quartzite_stone', 994, 250)
                .chancedOutput('gregicsifting:chunk.barite_stone', 553, 250)
                .chancedOutput('gregicsifting:chunk.certus_quartz_stone', 663, 250)
                .chancedOutput('gregicsifting:chunk.tin_stone', 2422, 250)
                .chancedOutput('gregicsifting:chunk.bornite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.chalcocite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.copper_stone', 323, 250)
                .chancedOutput('gregicsifting:chunk.galena_stone', 1040, 250)
                .chancedOutput('gregicsifting:chunk.lead_stone', 520, 250)
                .chancedOutput('gregicsifting:chunk.silver_stone', 520, 250)
                .chancedOutput('gregicsifting:chunk.lazurite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.sodalite_stone', 390, 250)
                .chancedOutput('gregicsifting:chunk.lapis_stone', 683, 250)
                .chancedOutput('gregicsifting:chunk.calcite_stone', 292, 250)
                .duration(100)
                .EUt(24);
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:diorite_sifting_type_steel')
                .chance(0)
                .itemInputs('exnihilosequentia:iron_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_diorite')
                .chancedOutput('gregicsifting:chunk.bauxite_stone', 1530, 250)
                .chancedOutput('gregicsifting:chunk.aluminium_stone', 765, 250)
                .chancedOutput('gregicsifting:chunk.ilmenite_stone', 255, 250)
                .chancedOutput('gregicsifting:chunk.chalcopyrite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 808, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.alunite_stone', 195, 250)
                .chancedOutput('gregicsifting:chunk.quartzite_stone', 994, 250)
                .chancedOutput('gregicsifting:chunk.barite_stone', 553, 250)
                .chancedOutput('gregicsifting:chunk.certus_quartz_stone', 663, 250)
                .chancedOutput('gregicsifting:chunk.tin_stone', 2422, 250)
                .chancedOutput('gregicsifting:chunk.bornite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.chalcocite_stone', 969, 250)
                .chancedOutput('gregicsifting:chunk.copper_stone', 323, 250)
                .chancedOutput('gregicsifting:chunk.galena_stone', 1040, 250)
                .chancedOutput('gregicsifting:chunk.lead_stone', 520, 250)
                .chancedOutput('gregicsifting:chunk.silver_stone', 520, 250)
                .chancedOutput('gregicsifting:chunk.lazurite_stone', 585, 250)
                .chancedOutput('gregicsifting:chunk.sodalite_stone', 390, 250)
                .chancedOutput('gregicsifting:chunk.lapis_stone', 683, 250)
                .chancedOutput('gregicsifting:chunk.calcite_stone', 292, 250)
                .chancedOutput('gregicsifting:chunk.yellow_limonite_stone', 507, 250)
                .chancedOutput('gregicsifting:chunk.malachite_stone', 169, 250)
                .chancedOutput('gregicsifting:chunk.pitchblende_stone', 845, 250)
                .chancedOutput('gregicsifting:chunk.uraninite_stone', 676, 250)
                .chancedOutput('gregicsifting:chunk.kyanite_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.mica_stone', 546, 250)
                .chancedOutput('gregicsifting:chunk.cassiterite_stone', 364, 250)
                .chancedOutput('gregicsifting:chunk.pollucite_stone', 364, 250)
                .duration(100)
                .EUt(24);
        //Diorite-End
            function dioriteChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:diorite_sifting_type_${id}`)
                    .chance(0)
                    .itemInputs(`exnihilosequentia:${mesh}_mesh`)
                    .chance(1)
                    .itemInputs('exnihilosequentia:crushed_diorite')
                    .chancedOutput('gregicsifting:chunk.bauxite_stone', 1530, boost)
                    .chancedOutput('gregicsifting:chunk.aluminium_stone', 765, boost)
                    .chancedOutput('gregicsifting:chunk.ilmenite_stone', 255, boost)
                    .chancedOutput('gregicsifting:chunk.chalcopyrite_stone', 585, boost)
                    .chancedOutput('gregicsifting:chunk.cassiterite_stone', 808, boost)
                    .chancedOutput('gregicsifting:chunk.cassiterite_stone', 585, boost)
                    .chancedOutput('gregicsifting:chunk.alunite_stone', 195, boost)
                    .chancedOutput('gregicsifting:chunk.quartzite_stone', 994, boost)
                    .chancedOutput('gregicsifting:chunk.barite_stone', 553, boost)
                    .chancedOutput('gregicsifting:chunk.certus_quartz_stone', 663, boost)
                    .chancedOutput('gregicsifting:chunk.tin_stone', 2422, boost)
                    .chancedOutput('gregicsifting:chunk.bornite_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.chalcocite_stone', 969, boost)
                    .chancedOutput('gregicsifting:chunk.copper_stone', 323, boost)
                    .chancedOutput('gregicsifting:chunk.galena_stone', 1040, boost)
                    .chancedOutput('gregicsifting:chunk.lead_stone', 520, boost)
                    .chancedOutput('gregicsifting:chunk.silver_stone', 520, boost)
                    .chancedOutput('gregicsifting:chunk.lazurite_stone', 585, boost)
                    .chancedOutput('gregicsifting:chunk.sodalite_stone', 390, boost)
                    .chancedOutput('gregicsifting:chunk.lapis_stone', 683, boost)
                    .chancedOutput('gregicsifting:chunk.calcite_stone', 292, boost)
                    .chancedOutput('gregicsifting:chunk.yellow_limonite_stone', 507, boost)
                    .chancedOutput('gregicsifting:chunk.malachite_stone', 169, boost)
                    .chancedOutput('gregicsifting:chunk.pitchblende_stone', 845, boost)
                    .chancedOutput('gregicsifting:chunk.uraninite_stone', 676, boost)
                    .chancedOutput('gregicsifting:chunk.kyanite_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.mica_stone', 546, boost)
                    .chancedOutput('gregicsifting:chunk.cassiterite_stone', 364, boost)
                    .chancedOutput('gregicsifting:chunk.pollucite_stone', 364, boost)
                    .chancedOutput('gregicsifting:chunk.graphite_stone', 1014, boost)
                    .chancedOutput('gregicsifting:chunk.diamond_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.coal_stone', 338, boost)
                    .chancedOutput('gregicsifting:chunk.soapstone_stone', 560, boost)
                    .chancedOutput('gregicsifting:chunk.talc_stone', 560, boost)
                    .chancedOutput('gregicsifting:chunk.pentlandite_stone', 560, boost)
                    .duration(100)
                    .EUt(24);

            }
                    //Aluminium
                        dioriteChance('aluminium', 'diamond', 350)
                    //Stainless
                        dioriteChance('stainless', 'emerald', 450)
                    //Titanium
                        dioriteChance('titanium', 'netherrite', 500)
    //Netherrack
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:netherrack_sifting_type_bronze')
                .chance(0)
                .itemInputs('exnihilosequentia:flint_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_netherrack')
                .chancedOutput('gregicsifting:chunk.chalcopyrite_nether', 432, 250)
                .chancedOutput('gregicsifting:chunk.iron_nether', 357, 250)
                .chancedOutput('gregicsifting:chunk.iron_nether', 432, 250)
                .chancedOutput('gregicsifting:chunk.pyrite_nether', 544, 250)
                .chancedOutput('gregicsifting:chunk.pyrite_nether', 432, 250)
                .chancedOutput('gregicsifting:chunk.copper_nether', 144, 250)
                .chancedOutput('gregicsifting:chunk.copper_nether', 312, 250)
                .chancedOutput('gregicsifting:chunk.yellow_limonite_nether', 324, 250)
                .chancedOutput('gregicsifting:chunk.malachite_nether', 108, 250)
                .chancedOutput('gregicsifting:chunk.magnetite_nether', 1428, 250)
                .chancedOutput('gregicsifting:chunk.vanadium_magnetite_nether', 357, 250)
                .chancedOutput('gregicsifting:chunk.gold_nether', 238, 250)
                .chancedOutput('gregicsifting:chunk.nether_quartz_nether', 3240, 250)
                .chancedOutput('gregicsifting:chunk.sulfur_nether', 1632, 250)
                .chancedOutput('gregicsifting:chunk.sphalerite_nether', 544, 250)
                .chancedOutput('gregicsifting:chunk.tetrahedrite_nether', 936, 250)
                .chancedOutput('gregicsifting:chunk.stibnite_nether', 312, 250)
                .duration(100)
                .EUt(24);
        //Netherrack-End
            function netherChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:netherrack_sifting_type_${id}`)
                    .chance(0)
                    .itemInputs(`exnihilosequentia:${mesh}_mesh`)
                    .chance(1)
                    .itemInputs('exnihilosequentia:crushed_netherrack')
                    .chancedOutput('gregicsifting:chunk.chalcopyrite_nether', 432, boost)
                    .chancedOutput('gregicsifting:chunk.iron_nether', 357, boost)
                    .chancedOutput('gregicsifting:chunk.iron_nether', 432, boost)
                    .chancedOutput('gregicsifting:chunk.pyrite_nether', 544, boost)
                    .chancedOutput('gregicsifting:chunk.pyrite_nether', 432, boost)
                    .chancedOutput('gregicsifting:chunk.copper_nether', 144, boost)
                    .chancedOutput('gregicsifting:chunk.copper_nether', 312, boost)
                    .chancedOutput('gregicsifting:chunk.yellow_limonite_nether', 324, boost)
                    .chancedOutput('gregicsifting:chunk.malachite_nether', 108, boost)
                    .chancedOutput('gregicsifting:chunk.magnetite_nether', 1428, boost)
                    .chancedOutput('gregicsifting:chunk.vanadium_magnetite_nether', 357, boost)
                    .chancedOutput('gregicsifting:chunk.gold_nether', 238, boost)
                    .chancedOutput('gregicsifting:chunk.nether_quartz_nether', 3240, boost)
                    .chancedOutput('gregicsifting:chunk.sulfur_nether', 1632, boost)
                    .chancedOutput('gregicsifting:chunk.sphalerite_nether', 544, boost)
                    .chancedOutput('gregicsifting:chunk.tetrahedrite_nether', 936, boost)
                    .chancedOutput('gregicsifting:chunk.stibnite_nether', 312, boost)
                    .chancedOutput('gregicsifting:chunk.garnierite_nether', 189, boost)
                    .chancedOutput('gregicsifting:chunk.nickel_nether', 189, boost)
                    .chancedOutput('gregicsifting:chunk.cobaltite_nether', 189, boost)
                    .chancedOutput('gregicsifting:chunk.pentlandite_nether', 63, boost)
                    .chancedOutput('gregicsifting:chunk.redstone_nether', 864, boost)
                    .chancedOutput('gregicsifting:chunk.ruby_nether', 288, boost)
                    .chancedOutput('gregicsifting:chunk.cinnabar_nether', 288, boost)
                    .chancedOutput('gregicsifting:chunk.chromite_nether', 72, boost)
                    .chancedOutput('gregicsifting:chunk.electrotine_nether', 72, boost)
                    .chancedOutput('gregicsifting:chunk.topaz_nether', 294, boost)
                    .chancedOutput('gregicsifting:chunk.blue_topaz_nether', 196, boost)
                    .duration(100)
                    .EUt(24);

            }
                    //Aluminium
                        netherChance('aluminium', 'diamond', 350)
                    //Stainless
                        netherChance('stainless', 'emerald', 450)
                    //Titanium
                        netherChance('titanium', 'netherrite', 500)
    //Endstone
        //Bronze
            event.recipes.gtceu.electric_sieve('gtceu:endstone_sifting_type_bronze')
                .chance(0)
                .itemInputs('exnihilosequentia:flint_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_end_stone')
                .chancedOutput('gregicsifting:chunk.beryllium_end', 405, 250)
                .chancedOutput('gregicsifting:chunk.emerald_end', 243, 250)
                .chancedOutput('gregicsifting:chunk.thorium_end', 162, 250)
                .duration(100)
                .EUt(24);
        //Steel
            event.recipes.gtceu.electric_sieve('gtceu:endstone_sifting_type_steel')
                .chance(0)
                .itemInputs('exnihilosequentia:iron_mesh')
                .chance(1)
                .itemInputs('exnihilosequentia:crushed_end_stone')
                .chancedOutput('gregicsifting:chunk.beryllium_end', 405, 250)
                .chancedOutput('gregicsifting:chunk.emerald_end', 243, 250)
                .chancedOutput('gregicsifting:chunk.thorium_end', 162, 250)
                .chancedOutput('gregicsifting:chunk.grossular_end', 192, 250)
                .chancedOutput('gregicsifting:chunk.spessartine_end', 192, 250)
                .chancedOutput('gregicsifting:chunk.pyrolusite_end', 192, 250)
                .chancedOutput('gregicsifting:chunk.tantalite_end', 64, 250)
                .chancedOutput('gregicsifting:chunk.wulfenite_end', 256, 250)
                .chancedOutput('gregicsifting:chunk.molybdenite_end', 256, 250)
                .chancedOutput('gregicsifting:chunk.powellite_end', 128, 250)
                .chancedOutput('gregicsifting:chunk.garnierite_end', 189, 250)
                .chancedOutput('gregicsifting:chunk.nickel_end', 189, 250)
                .chancedOutput('gregicsifting:chunk.cobaltite_end', 189, 250)
                .chancedOutput('gregicsifting:chunk.pentlandite_end', 63, 250)
                .chancedOutput('gregicsifting:chunk.bentonite_end', 192, 250)
                .chancedOutput('gregicsifting:chunk.magnesite_end', 192, 250)
                .chancedOutput('gregicsifting:chunk.olivine_end', 192, 250)
                .chancedOutput('gregicsifting:chunk.chromite_end', 640, 250)
                .chancedOutput('gregicsifting:chunk.sheldonite_end', 288, 250)
                .chancedOutput('gregicsifting:chunk.palladium_end', 224, 250)
                .chancedOutput('gregicsifting:chunk.scheelite_end', 384, 250)
                .chancedOutput('gregicsifting:chunk.tungstate_end', 128, 250)
                .chancedOutput('gregicsifting:chunk.lithium_end', 128, 250)
                .duration(100)
                .EUt(24);
        //Endstone-End
            function endChance(id, mesh, boost) {
                event.recipes.gtceu.electric_sieve(`gtceu:endstone_sifting_type_${id}`)
                    .chance(0)
                    .itemInputs(`exnihilosequentia:${mesh}_mesh`)
                    .chance(1)
                    .itemInputs('exnihilosequentia:crushed_end_stone')
                    .chancedOutput('gregicsifting:chunk.beryllium_end', 405, boost)
                    .chancedOutput('gregicsifting:chunk.emerald_end', 243, boost)
                    .chancedOutput('gregicsifting:chunk.thorium_end', 162, boost)
                    .chancedOutput('gregicsifting:chunk.grossular_end', 192, boost)
                    .chancedOutput('gregicsifting:chunk.spessartine_end', 192, boost)
                    .chancedOutput('gregicsifting:chunk.pyrolusite_end', 192, boost)
                    .chancedOutput('gregicsifting:chunk.tantalite_end', 64, boost)
                    .chancedOutput('gregicsifting:chunk.wulfenite_end', 256, boost)
                    .chancedOutput('gregicsifting:chunk.molybdenite_end', 256, boost)
                    .chancedOutput('gregicsifting:chunk.powellite_end', 128, boost)
                    .chancedOutput('gregicsifting:chunk.garnierite_end', 189, boost)
                    .chancedOutput('gregicsifting:chunk.nickel_end', 189, boost)
                    .chancedOutput('gregicsifting:chunk.cobaltite_end', 189, boost)
                    .chancedOutput('gregicsifting:chunk.pentlandite_end', 63, boost)
                    .chancedOutput('gregicsifting:chunk.bentonite_end', 192, boost)
                    .chancedOutput('gregicsifting:chunk.magnesite_end', 192, boost)
                    .chancedOutput('gregicsifting:chunk.olivine_end', 192, boost)
                    .chancedOutput('gregicsifting:chunk.chromite_end', 640, boost)
                    .chancedOutput('gregicsifting:chunk.sheldonite_end', 288, boost)
                    .chancedOutput('gregicsifting:chunk.palladium_end', 224, boost)
                    .chancedOutput('gregicsifting:chunk.scheelite_end', 384, boost)
                    .chancedOutput('gregicsifting:chunk.tungstate_end', 128, boost)
                    .chancedOutput('gregicsifting:chunk.lithium_end', 128, boost)
                    .chancedOutput('gregicsifting:chunk.naquadah_end', 3600, boost)
                    .chancedOutput('gregicsifting:chunk.lazurite_end', 216, boost)
                    .chancedOutput('gregicsifting:chunk.sodalite_end', 144, boost)
                    .chancedOutput('gregicsifting:chunk.lapis_end', 252, boost)
                    .chancedOutput('gregicsifting:chunk.calcite_end', 108, boost)
                    .duration(100)
                    .EUt(24);

            }
                    //Aluminium
                        endChance('aluminium', 'diamond', 350)
                    //Stainless
                        endChance('stainless', 'emerald', 450)
                    //Titanium
                        endChance('titanium', 'netherrite', 500)
})
