ServerEvents.recipes(event => {
    function ForgeHammer(Ore, Crushed, ID){
        event.recipes.gtceu.forge_hammer(`gtceu:hammer_${ID}_ore_chunk_to_crushed_ore`)
        .itemInputs(Ore)
        .itemOutputs(Crushed)
        .duration(10)
        .EUt(16)   
    }
    //Gravel
        //String
            ForgeHammer('gregicsifting:chunk.gypsum_stone', '1x gtceu:gypsum_crushed_ore', 'stone_gypsum')
            ForgeHammer('gregicsifting:chunk.spodumene_stone', '1x gtceu:spodumene_crushed_ore', 'stone_spodumene')
            ForgeHammer('gregicsifting:chunk.cassiterite_stone', '2x gtceu:cassiterite_crushed_ore', 'stone_cassiterite')
            ForgeHammer('gregicsifting:chunk.coal_stone', '2x gtceu:coal_crushed_ore', 'stone_coal')
            ForgeHammer('gregicsifting:chunk.trona_stone', '2x gtceu:trona_crushed_ore', 'stone_trona')
            ForgeHammer('gregicsifting:chunk.fullers_earth_stone', '2x gtceu:fullers_earth_crushed_ore', 'stone_fullers_earth')
            ForgeHammer('gregicsifting:chunk.basaltic_mineral_stone', '1x gtceu:basaltic_mineral_sand_crushed_ore', 'stone_basaltic_mineral_sand')
            ForgeHammer('gregicsifting:chunk.salt_stone', '2x gtceu:salt_crushed_ore', 'stone_salt')
            ForgeHammer('gregicsifting:chunk.granitic_mineral_stone', '1x gtceu:granitic_mineral_sand_crushed_ore', 'stone_granitic_mineral_sand')
            ForgeHammer('gregicsifting:chunk.tin_stone', '1x gtceu:tin_crushed_ore', 'stone_tin')
            ForgeHammer('gregicsifting:chunk.rock_salt_stone', '2x gtceu:rock_salt_crushed_ore', 'stone_rock_salt')
            ForgeHammer('gregicsifting:chunk.lepidolite_stone', '2x gtceu:lepidolite_crushed_ore', 'stone_lepidolite')
        //Bronze
            ForgeHammer('gregicsifting:chunk.galena_stone', '1x gtceu:galena_crushed_ore', 'stone_galena')
            ForgeHammer('gregicsifting:chunk.lead_stone', '1x gtceu:lead_crushed_ore', 'stone_lead')
            ForgeHammer('gregicsifting:chunk.silver_stone', '1x gtceu:silver_crushed_ore', 'stone_silver')
            ForgeHammer('gregicsifting:chunk.zeolite_stone', '3x gtceu:zeolite_crushed_ore', 'stone_zeolite')
            ForgeHammer('gregicsifting:chunk.glauconite_sand_stone', '3x gtceu:glauconite_sand_crushed_ore', 'stone_glauconite_sand')
            ForgeHammer('gregicsifting:chunk.oilsands_stone', '1x gtceu:oilsands_crushed_ore', 'stone_oilsands')
            ForgeHammer('gregicsifting:chunk.garnet_sand_stone', '1x gtceu:garnet_sand_crushed_ore', 'stone_garnet_sand')
            ForgeHammer('gregicsifting:chunk.asbestos_stone', '3x gtceu:asbestos_crushed_ore', 'stone_asbestos')
            ForgeHammer('gregicsifting:chunk.diatomite_stone', '1x gtceu:diatomite_crushed_ore', 'stone_diatomite')
        //Steel
            ForgeHammer('gregicsifting:chunk.platinum_stone', '1x gtceu:platinum_crushed_ore', 'stone_platinum')
            ForgeHammer('gregicsifting:chunk.palladium_stone', '1x gtceu:palladium_crushed_ore', 'stone_palladium')
    //Sand
        //Bronze
            ForgeHammer('gregicsifting:chunk.copper_sand', 'gtceu:copper_crushed_ore', 'sand_copper')
            ForgeHammer('gregicsifting:chunk.redstone_sand', '5x gtceu:redstone_crushed_ore', 'sand_redstone')
            ForgeHammer('gregicsifting:chunk.cinnabar_sand', 'gtceu:cinnabar_gem', 'sand_cinnabar')
            ForgeHammer('gregicsifting:chunk.chromite_sand', 'gtceu:chromite_crushed_ore', 'sand_chromite')
            ForgeHammer('gregicsifting:chunk.pyrope_sand', '3x gtceu:pyrope_gem', 'sand_pyrope')
            ForgeHammer('gregicsifting:chunk.sapphire_sand', 'gtceu:sapphire_gem', 'sand_sapphire')
            ForgeHammer('gregicsifting:chunk.green_sapphire_sand', 'gtceu:green_sapphire_gem', 'sand_green_sapphire')
        //Steel
            ForgeHammer('gregicsifting:chunk.chalcopyrite_sand', 'gtceu:chalcopyrite_crushed_ore', 'sand_chalcopyrite')
            ForgeHammer('gregicsifting:chunk.iron_sand', 'gtceu:iron_crushed_ore', 'sand_iron')
            ForgeHammer('gregicsifting:chunk.pyrite_sand', 'gtceu:pyrite_crushed_ore', 'sand_pyrite')
            ForgeHammer('gregicsifting:chunk.yellow_limonite_sand', 'gtceu:yellow_limonite_crushed_ore', 'sand_yellow_limonite')
            ForgeHammer('gregicsifting:chunk.malachite_sand', 'gtceu:malachite_crushed_ore', 'sand_malachite')
            ForgeHammer('gregicsifting:chunk.garnierite_sand', 'gtceu:garnierite_crushed_ore', 'sand_garnierite')
            ForgeHammer('gregicsifting:chunk.nickel_sand', 'gtceu:nickel_crushed_ore', 'sand_nickel')
            ForgeHammer('gregicsifting:chunk.cobaltite_sand', 'gtceu:cobaltite_crushed_ore', 'sand_cobaltite')
            ForgeHammer('gregicsifting:chunk.pentlandite_sand', 'gtceu:pentlandite_crushed_ore', 'sand_pentlandite')
            ForgeHammer('gregicsifting:chunk.bentonite_sand', 'gtceu:bentonite_crushed_ore', 'sand_bentonite')
            ForgeHammer('gregicsifting:chunk.magnesite_sand', 'gtceu:magnesite_crushed_ore', 'sand_magnesite')
            ForgeHammer('gregicsifting:chunk.olivine_sand', '2x gtceu:olivine_gem', 'sand_olivine')
        //Aluminium
            ForgeHammer('gregicsifting:chunk.beryllium_sand', 'gtceu:beryllium_crushed_ore', 'sand_beryllium')
            ForgeHammer('gregicsifting:chunk.emerald_sand', '2x gtceu:emerald_crushed_ore', 'sand_emerald')
            ForgeHammer('gregicsifting:chunk.thorium_sand', 'gtceu:thorium_crushed_ore', 'sand_thorium')
            ForgeHammer('gregicsifting:chunk.grossular_sand', '3x gtceu:grossular_gem', 'sand_grossular')
            ForgeHammer('gregicsifting:chunk.spessartine_sand', '3x gtceu:spessartine_gem', 'sand_spessartine')
            ForgeHammer('gregicsifting:chunk.pyrolusite_sand', 'gtceu:pyrolusite_crushed_ore', 'sand_pyrolusite')
            ForgeHammer('gregicsifting:chunk.tantalite_sand', 'gtceu:tantalite_crushed_ore', 'sand_tantalite')
    //Andesite
        //Bronze
            ForgeHammer('gregicsifting:chunk.redstone_stone', '5x gtceu:redstone_crushed_ore', 'stone_redstone')
            ForgeHammer('gregicsifting:chunk.ruby_stone', 'gtceu:ruby_gem', 'stone_ruby')
            ForgeHammer('gregicsifting:chunk.cinnabar_stone', 'gtceu:cinnabar_gem', 'stone_cinnabar')
            ForgeHammer('gregicsifting:chunk.chromite_stone', 'gtceu:chromite_crushed_ore', 'stone_chromite')
            ForgeHammer('gregicsifting:chunk.almandine_stone', '3x gtceu:almandine_gem', 'stone_almandine')
            ForgeHammer('gregicsifting:chunk.pyrope_stone', '3x gtceu:pyrope_gem', 'stone_pyrope')
            ForgeHammer('gregicsifting:chunk.sapphire_stone', 'gtceu:sapphire_gem', 'stone_sapphire')
            ForgeHammer('gregicsifting:chunk.green_sapphire_stone', 'gtceu:green_sapphire_gem', 'stone_green_sapphire')
            ForgeHammer('gregicsifting:chunk.topaz_stone', 'gtceu:topaz_gem', 'stone_topaz')
            ForgeHammer('gregicsifting:chunk.blue_topaz_stone', '2x gtceu:blue_topaz_gem', 'stone_blue_topaz')
        //Steel
            ForgeHammer('gregicsifting:chunk.chalcopyrite_stone', 'gtceu:chalcopyrite_crushed_ore', 'stone_chalcopyrite')
            ForgeHammer('gregicsifting:chunk.iron_stone', 'gtceu:iron_crushed_ore', 'stone_iron')
            ForgeHammer('gregicsifting:chunk.pyrite_stone', 'gtceu:pyrite_crushed_ore', 'stone_pyrite')
            ForgeHammer('gregicsifting:chunk.yellow_limonite_stone', 'gtceu:yellow_limonite_crushed_ore', 'stone_yellow_limonite')
            ForgeHammer('gregicsifting:chunk.malachite_stone', 'gtceu:malachite_crushed_ore', 'stone_malachite')
            ForgeHammer('gregicsifting:chunk.bastnasite_stone', '2x gtceu:bastnasite_crushed_ore', 'stone_bastnasite')
            ForgeHammer('gregicsifting:chunk.monazite_stone', '4x gtceu:monazite_gem', 'stone_monazite')
            ForgeHammer('gregicsifting:chunk.neodymium_stone', 'gtceu:neodymium_crushed_ore', 'stone_neodymium')
            ForgeHammer('gregicsifting:chunk.garnierite_stone', 'gtceu:garnierite_crushed_ore', 'stone_garnierite')
            ForgeHammer('gregicsifting:chunk.nickel_stone', 'gtceu:nickel_crushed_ore', 'stone_nickel')
            ForgeHammer('gregicsifting:chunk.cobaltite_stone', 'gtceu:cobaltite_crushed_ore', 'stone_cobaltite')
            ForgeHammer('gregicsifting:chunk.pentlandite_stone', 'gtceu:pentlandite_crushed_ore', 'stone_pentlandite')
            ForgeHammer('gregicsifting:chunk.bentonite_stone', 'gtceu:bentonite_crushed_ore', 'stone_bentonite')
            ForgeHammer('gregicsifting:chunk.magnesite_stone', 'gtceu:magnesite_crushed_ore', 'stone_magnesite')
            ForgeHammer('gregicsifting:chunk.olivine_stone', '2x gtceu:olivine_gem', 'stone_olivine')
            ForgeHammer('gregicsifting:chunk.pitchblende_stone', 'gtceu:pitchblende_crushed_ore', 'stone_pitchblende')
            ForgeHammer('gregicsifting:chunk.uraninite_stone', 'gtceu:uraninite_crushed_ore', 'stone_uraninite')
            ForgeHammer('gregicsifting:chunk.graphite_stone', 'gtceu:graphite_crushed_ore', 'stone_graphite')
            ForgeHammer('gregicsifting:chunk.diamond_stone', 'gtceu:diamond_crushed_ore', 'stone_diamond')
            //coal on line - 117
        //Aluminium
            ForgeHammer('gregicsifting:chunk.beryllium_stone', 'gtceu:beryllium_crushed_ore', 'stone_beryllium')
            ForgeHammer('gregicsifting:chunk.emerald_stone', '2x gtceu:emerald_crushed_ore', 'stone_emerald')
            ForgeHammer('gregicsifting:chunk.thorium_stone', 'gtceu:thorium_crushed_ore', 'stone_thorium')
            ForgeHammer('gregicsifting:chunk.soapstone_stone', '3x gtceu:soapstone_crushed_ore', 'stone_soapstone')
            ForgeHammer('gregicsifting:chunk.talc_stone', '2x gtceu:talc_crushed_ore', 'stone_talc')
            ForgeHammer('gregicsifting:chunk.scheelite_stone', 'gtceu:scheelite_crushed_ore', 'stone_scheelite')
            ForgeHammer('gregicsifting:chunk.tungstate_stone', 'gtceu:tungstate_crushed_ore', 'stone_tungstate')
            ForgeHammer('gregicsifting:chunk.lithium_stone', 'gtceu:lithium_crushed_ore', 'stone_lithium')
    //Granite
        //String
            ForgeHammer('gregicsifting:chunk.apatite_stone', '4x gtceu:apatite_gem', 'stone_apatite')
            ForgeHammer('gregicsifting:chunk.tricalcium_phosphate_stone', '3x gtceu:tricalcium_phosphate_crushed_ore', 'stone_tricalcium_phosphate')
            ForgeHammer('gregicsifting:chunk.bauxite_stone', 'gtceu:bauxite_crushed_ore', 'stone_bauxite')
            ForgeHammer('gregicsifting:chunk.aluminium_stone', 'gtceu:aluminium_crushed_ore', 'stone_aluminium')
            ForgeHammer('gregicsifting:chunk.ilmenite_stone', 'gtceu:ilmenite_crushed_ore', 'stone_ilmenite')
            ForgeHammer('gregicsifting:chunk.magnetite_stone', 'gtceu:magnetite_crushed_ore', 'stone_magnetite')
            ForgeHammer('gregicsifting:chunk.vanadium_magnetite_stone', 'gtceu:vanadium_magnetite_crushed_ore', 'stone_vanadium_magnetite')
            ForgeHammer('gregicsifting:chunk.gold_stone', 'gtceu:gold_crushed_ore', 'stone_gold')
            ForgeHammer('gregicsifting:chunk.quartzite_stone', '2x gtceu:quartzite_gem', 'stone_quartzite')
            ForgeHammer('gregicsifting:chunk.barite_stone', 'gtceu:barite_crushed_ore', 'stone_barite')
            ForgeHammer('gregicsifting:chunk.certus_quartz_stone', '2x gtceu:certus_quartz_gem', 'stone_certus_quartz')
            ForgeHammer('gregicsifting:chunk.tetrahedrite_stone', 'gtceu:tetrahedrite_crushed_ore', 'stone_tetrahedrite')
            ForgeHammer('gregicsifting:chunk.stibnite_stone', 'gtceu:stibnite_crushed_ore', 'stone_stibnite')
        //Bronze
            ForgeHammer('gregicsifting:chunk.bornite_stone', 'gtceu:bornite_crushed_ore', 'stone_bornite')
            ForgeHammer('gregicsifting:chunk.chalcocite_stone', 'gtceu:chalcocite_crushed_ore', 'stone_chalcocite')
            ForgeHammer('gregicsifting:chunk.lazurite_stone', '6x gtceu:lazurite_gem', 'stone_lazurite')
            ForgeHammer('gregicsifting:chunk.sodalite_stone', '6x gtceu:sodalite_gem', 'stone_sodalite')
            ForgeHammer('gregicsifting:chunk.lapis_stone', '6x gtceu:lapis_crushed_ore', 'stone_lapis')
            ForgeHammer('gregicsifting:chunk.calcite_stone', 'gtceu:calcite_crushed_ore', 'stone_calcite')
        //Steel
            ForgeHammer('gregicsifting:chunk.kyanite_stone', 'gtceu:kyanite_crushed_ore', 'stone_kyanite')
            ForgeHammer('gregicsifting:chunk.mica_stone', '2x gtceu:mica_crushed_ore', 'stone_mica')
            ForgeHammer('gregicsifting:chunk.pollucite_stone', 'gtceu:pollucite_crushed_ore', 'stone_pollucite')
        //Aluminium
            ForgeHammer('gregicsifting:chunk.wulfenite_stone', 'gtceu:wulfenite_crushed_ore', 'stone_wulfenite')
            ForgeHammer('gregicsifting:chunk.molybdenite_stone', 'gtceu:molybdenite_crushed_ore', 'stone_molybdenite')
            ForgeHammer('gregicsifting:chunk.powellite_stone', 'gtceu:powellite_crushed_ore', 'stone_powellite')
    //Diorite
        //String
            ForgeHammer('gregicsifting:chunk.alunite_stone', '3x gtceu:alunite_crushed_ore', 'stone_alunite')
            //Tin
        //Bronze
        //Steel
        //Aluminium
    //Netherrack
        //Bronze
            ForgeHammer('gregicsifting:chunk.chalcopyrite_nether', '2x gtceu:chalcopyrite_crushed_ore', 'nether_chalcopyrite')
            ForgeHammer('gregicsifting:chunk.iron_nether', '2x gtceu:iron_crushed_ore', 'nether_iron')
            ForgeHammer('gregicsifting:chunk.pyrite_nether', '2x gtceu:pyrite_crushed_ore', 'nether_pyrite')
            ForgeHammer('gregicsifting:chunk.copper_nether', '2x gtceu:copper_crushed_ore', 'nether_copper')
            ForgeHammer('gregicsifting:chunk.yellow_limonite_nether', '2x gtceu:yellow_limonite_crushed_ore', 'nether_yellow_limonite')
            ForgeHammer('gregicsifting:chunk.malachite_nether', '2x gtceu:malachite_crushed_ore', 'nether_malachite')
            ForgeHammer('gregicsifting:chunk.magnetite_nether', '2x gtceu:magnetite_crushed_ore', 'nether_magnetite')
            ForgeHammer('gregicsifting:chunk.vanadium_magnetite_nether', '2x gtceu:vanadium_magnetite_crushed_ore', 'nether_vanadium_magnetite')
            ForgeHammer('gregicsifting:chunk.gold_nether', '2x gtceu:gold_crushed_ore', 'nether_gold')
            ForgeHammer('gregicsifting:chunk.nether_quartz_nether', '4x gtceu:nether_quartz_crushed_ore', 'nether_nether_quartz')
            ForgeHammer('gregicsifting:chunk.sulfur_nether', '2x gtceu:sulfur_crushed_ore', 'nether_sulfur')
            ForgeHammer('gregicsifting:chunk.sphalerite_nether', '2x gtceu:sphalerite_crushed_ore', 'nether_sphalerite')
            ForgeHammer('gregicsifting:chunk.tetrahedrite_nether', '2x gtceu:tetrahedrite_crushed_ore', 'nether_tetrahedrite')
            ForgeHammer('gregicsifting:chunk.stibnite_nether', '2x gtceu:stibnite_crushed_ore', 'nether_stibnite')
        //Aluminium
            ForgeHammer('gregicsifting:chunk.garnierite_nether', '2x gtceu:garnierite_crushed_ore', 'nether_garnierite')
            ForgeHammer('gregicsifting:chunk.nickel_nether', '2x gtceu:nickel_crushed_ore', 'nether_nickel')
            ForgeHammer('gregicsifting:chunk.cobaltite_nether', '2x gtceu:cobaltite_crushed_ore', 'nether_cobaltite')
            ForgeHammer('gregicsifting:chunk.pentlandite_nether', '2x gtceu:pentlandite_crushed_ore', 'nether_pentlandite')
            ForgeHammer('gregicsifting:chunk.redstone_nether', '10x gtceu:redstone_crushed_ore', 'nether_redstone')
            ForgeHammer('gregicsifting:chunk.ruby_nether', '2x gtceu:ruby_gem', 'nether_ruby')
            ForgeHammer('gregicsifting:chunk.cinnabar_nether', '2x gtceu:cinnabar_gem', 'nether_cinnabar')
            ForgeHammer('gregicsifting:chunk.chromite_nether', '2x gtceu:chromite_crushed_ore', 'nether_chromite')
            ForgeHammer('gregicsifting:chunk.electrotine_nether', '10x gtceu:electrotine_crushed_ore', 'nether_electrotine')
            ForgeHammer('gregicsifting:chunk.topaz_nether', '2x gtceu:topaz_gem', 'nether_topaz')
            ForgeHammer('gregicsifting:chunk.blue_topaz_nether', '2x gtceu:blue_topaz_gem', 'nether_blue_topaz')
    //Endstone
        //Bronze
            ForgeHammer('gregicsifting:chunk.beryllium_end', '2x gtceu:beryllium_crushed_ore', 'end_emerald')
            ForgeHammer('gregicsifting:chunk.emerald_end', '4x gtceu:emerald_crushed_ore', 'end_emerald')
            ForgeHammer('gregicsifting:chunk.thorium_end', '2x gtceu:thorium_crushed_ore', 'end_thorium')
        //Steel
            ForgeHammer('gregicsifting:chunk.grossular_end', '6x gtceu:grossular_gem', 'end_grossular')
            ForgeHammer('gregicsifting:chunk.spessartine_end', '6x gtceu:spessartine_gem', 'end_spessartine')
            ForgeHammer('gregicsifting:chunk.pyrolusite_end', '2x gtceu:pyrolusite_crushed_ore', 'end_pyrolusite')
            ForgeHammer('gregicsifting:chunk.tantalite_end', '2x gtceu:tantalite_crushed_ore', 'end_tantalite')
            ForgeHammer('gregicsifting:chunk.wulfenite_end', '2x gtceu:wulfenite_crushed_ore', 'end_wulfenite')
            ForgeHammer('gregicsifting:chunk.molybdenite_end', '2x gtceu:molybdenite_crushed_ore', 'end_molybdenite')
            ForgeHammer('gregicsifting:chunk.powellite_end', '2x gtceu:powellite_crushed_ore', 'end_powellite')
            ForgeHammer('gregicsifting:chunk.garnierite_end', '2x gtceu:garnierite_crushed_ore', 'end_garnierite')
            ForgeHammer('gregicsifting:chunk.nickel_end', '2x gtceu:nickel_crushed_ore', 'end_nickel')
            ForgeHammer('gregicsifting:chunk.cobaltite_end', '2x gtceu:cobaltite_crushed_ore', 'end_cobaltite')
            ForgeHammer('gregicsifting:chunk.pentlandite_end', '2x gtceu:pentlandite_crushed_ore', 'end_pentlandite')
            ForgeHammer('gregicsifting:chunk.bentonite_end', '6x gtceu:bentonite_crushed_ore', 'end_bentonite')
            ForgeHammer('gregicsifting:chunk.magnesite_end', '2x gtceu:magnesite_crushed_ore', 'end_magnesite')
            ForgeHammer('gregicsifting:chunk.olivine_end', '4x gtceu:olivine_gem', 'end_olivine')
            ForgeHammer('gregicsifting:chunk.chromite_end', '2x gtceu:chromite_crushed_ore', 'end_chromite')
            ForgeHammer('gregicsifting:chunk.sheldonite_end', '2x gtceu:cooperite_crushed_ore', 'end_sheldonite')
            ForgeHammer('gregicsifting:chunk.palladium_end', '2x gtceu:palladium_crushed_ore', 'end_palladium')
            ForgeHammer('gregicsifting:chunk.scheelite_end', '2x gtceu:scheelite_crushed_ore', 'end_scheelite')
            ForgeHammer('gregicsifting:chunk.tungstate_end', '2x gtceu:tungstate_crushed_ore', 'end_tungstate')
            ForgeHammer('gregicsifting:chunk.lithium_end', '2x gtceu:lithium_crushed_ore', 'end_lithium')
        //Aluminium
            ForgeHammer('gregicsifting:chunk.naquadah_end', '2x gtceu:naquadah_crushed_ore', 'end_naquadah')
            ForgeHammer('gregicsifting:chunk.lazurite_end', '12x gtceu:lazurite_gem', 'end_lazurite')
            ForgeHammer('gregicsifting:chunk.sodalite_end', '12x gtceu:sodalite_gem', 'end_sodalite')
            ForgeHammer('gregicsifting:chunk.lapis_end', '12x minecraft:lapis_lazuli', 'end_lapis')
            ForgeHammer('gregicsifting:chunk.calcite_end', '2x gtceu:calcite_crushed_ore', 'end_calcite')
})
