ServerEvents.recipes(event => {
    let multiSmelt = (output, input, includeBlasting) => {
        event.smelting(output, input).xp(0.7)
        
        if (includeBlasting) {
          event.blasting(output, input).xp(0.7)
        }
      }
        //Gravel
            //String
                multiSmelt('gtceu:gypsum_dust','gregicsifting:chunk.gypsum_stone',true)
                multiSmelt('gtceu:spodumene_dust','gregicsifting:chunk.spodumene_stone',true)
                multiSmelt('2x gtceu:tin_ingot','gregicsifting:chunk.cassiterite_stone',true)
                multiSmelt('2x minecraft:coal','gregicsifting:chunk.coal_stone',true)
                multiSmelt('2x gtceu:trona_dust','gregicsifting:chunk.trona_stone',true)
                multiSmelt('2x gtceu:fullers_earth_dust','gregicsifting:chunk.fullers_earth_stone',true)
                multiSmelt('minecraft:iron_ingot','gregicsifting:chunk.basaltic_mineral_stone',true)
                multiSmelt('2x gtceu:salt_gem','gregicsifting:chunk.salt_stone',true)
                multiSmelt('minecraft:iron_ingot','gregicsifting:chunk.granitic_mineral_stone',true)
                multiSmelt('gtceu:tin_ingot','gregicsifting:chunk.tin_stone',true)
                multiSmelt('2x gtceu:rock_salt_gem','gregicsifting:chunk.rock_salt_stone',true)
                multiSmelt('2x gtceu:lepidolite_dust','gregicsifting:chunk.lepidolite_stone',true)
            //Bronze
                multiSmelt('gtceu:lead_ingot','gregicsifting:chunk.galena_stone',true)
                multiSmelt('gtceu:lead_ingot','gregicsifting:chunk.lead_stone',true)
                multiSmelt('gtceu:silver_ingot','gregicsifting:chunk.silver_stone',true)
                multiSmelt('3x gtceu:zeolite_dust','gregicsifting:chunk.zeolite_stone',true)
                multiSmelt('3x gtceu:glauconite_sand_dust','gregicsifting:chunk.glauconite_sand_stone',true)
                multiSmelt('gtceu:oilsands_dust','gregicsifting:chunk.oilsands_stone',true)
                multiSmelt('gtceu:garnet_sand_dust','gregicsifting:chunk.garnet_sand_stone',true)
                multiSmelt('3x gtceu:asbestos_dust','gregicsifting:chunk.asbestos_stone',true)
                multiSmelt('3x gtceu:diatomite_dust','gregicsifting:chunk.diatomite_stone',true)
            //Steel
                multiSmelt('gtceu:platinum_ingot','gregicsifting:chunk.platinum_stone',true)
        //Sand
            //Bronze
                multiSmelt('minecraft:copper_ingot', 'gregicsifting:chunk.copper_sand', true)
                multiSmelt('5x minecraft:redstone', 'gregicsifting:chunk.redstone_sand', true)
                multiSmelt('gtceu:cinnabar_gem', 'gregicsifting:chunk.cinnabar_sand', true)
                multiSmelt('gtceu:chromite_dust', 'gregicsifting:chunk.chromite_sand', true)
                multiSmelt('3x gtceu:pyrope_gem', 'gregicsifting:chunk.pyrope_sand', true)
                multiSmelt('gtceu:sapphire_gem', 'gregicsifting:chunk.sapphire_sand', true)
                multiSmelt('gtceu:green_sapphire_gem', 'gregicsifting:chunk.green_sapphire_sand', true)
            //Steel
                multiSmelt('minecraft:copper_ingot', 'gregicsifting:chunk.chalcopyrite_sand', true)
                multiSmelt('minecraft:iron_ingot', 'gregicsifting:chunk.iron_sand', true)
                multiSmelt('minecraft:iron_ingot', 'gregicsifting:chunk.pyrite_sand', true)
                multiSmelt('minecraft:iron_ingot', 'gregicsifting:chunk.yellow_limonite_sand', true)
                multiSmelt('minecraft:copper_ingot', 'gregicsifting:chunk.malachite_sand', true)
                multiSmelt('gtceu:nickel_ingot', 'gregicsifting:chunk.garnierite_sand', true)
                multiSmelt('gtceu:nickel_ingot', 'gregicsifting:chunk.nickel_sand', true)
                multiSmelt('gtceu:cobalt_ingot', 'gregicsifting:chunk.cobaltite_sand', true)
                multiSmelt('gtceu:nickel_ingot', 'gregicsifting:chunk.pentlandite_sand', true)
                multiSmelt('3x gtceu:bentonite_dust', 'gregicsifting:chunk.bentonite_sand', true)
                multiSmelt('gtceu:magnesium_dust', 'gregicsifting:chunk.magnesite_sand', true)
                multiSmelt('2x gtceu:olivine_gem', 'gregicsifting:chunk.olivine_sand', true)
            //Aluminium
                multiSmelt('gtceu:beryllium_ingot', 'gregicsifting:chunk.beryllium_sand', true)
                multiSmelt('minecraft:emerald', 'gregicsifting:chunk.emerald_sand', true)
                multiSmelt('gtceu:thorium_ingot', 'gregicsifting:chunk.thorium_sand', true)
                multiSmelt('3x gtceu:grossular_gem', 'gregicsifting:chunk.grossular_sand', true)
                multiSmelt('3x gtceu:spessartine_gem', 'gregicsifting:chunk.spessartine_sand', true)
                multiSmelt('gtceu:manganese_ingot', 'gregicsifting:chunk.pyrolusite_sand', true)
                multiSmelt('gtceu:tantalite_dust', 'gregicsifting:chunk.tantalite_sand', true)
        //Andesite
            //Bronze
                multiSmelt('5x minecraft:redstone', 'gregicsifting:chunk.redstone_stone', true)
                multiSmelt('gtceu:ruby_gem', 'gregicsifting:chunk.ruby_stone', true)
                multiSmelt('gtceu:cinnabar_gem', 'gregicsifting:chunk.cinnabar_stone', true)
                multiSmelt('gtceu:chromite_dust', 'gregicsifting:chunk.chromite_stone', true)
                multiSmelt('3x gtceu:almandine_gem', 'gregicsifting:chunk.almandine_stone', true)
                multiSmelt('3x gtceu:pyrope_gem', 'gregicsifting:chunk.pyrope_stone', true)
                multiSmelt('gtceu:sapphire_gem', 'gregicsifting:chunk.sapphire_stone', true)
                multiSmelt('gtceu:green_sapphire_gem', 'gregicsifting:chunk.green_sapphire_stone', true)
                multiSmelt('gtceu:topaz_gem', 'gregicsifting:chunk.topaz_stone', true)
                multiSmelt('gtceu:blue_topaz_gem', 'gregicsifting:chunk.blue_topaz_stone', true)
            //Steel
                multiSmelt('minecraft:copper_ingot', 'gregicsifting:chunk.chalcopyrite_stone', true)
                multiSmelt('minecraft:iron_ingot', 'gregicsifting:chunk.iron_stone', true)
                multiSmelt('minecraft:iron_ingot', 'gregicsifting:chunk.pyrite_stone', true)
                multiSmelt('minecraft:iron_ingot', 'gregicsifting:chunk.yellow_limonite_stone', true)
                multiSmelt('minecraft:copper_ingot', 'gregicsifting:chunk.malachite_stone', true)
                multiSmelt('2x gtceu:bastnasite_dust', 'gregicsifting:chunk.bastnasite_stone', true)
                multiSmelt('4x gtceu:monazite_gem', 'gregicsifting:chunk.monazite_stone', true)
                multiSmelt('gtceu:nickel_ingot', 'gregicsifting:chunk.garnierite_stone', true)
                multiSmelt('gtceu:nickel_ingot', 'gregicsifting:chunk.nickel_stone', true)
                multiSmelt('gtceu:cobalt_ingot', 'gregicsifting:chunk.cobaltite_stone', true)
                multiSmelt('gtceu:nickel_ingot', 'gregicsifting:chunk.pentlandite_stone', true)
                multiSmelt('3x gtceu:bentonite_dust', 'gregicsifting:chunk.bentonite_stone', true)
                multiSmelt('gtceu:magnesium_dust', 'gregicsifting:chunk.magnesite_stone', true)
                multiSmelt('2x gtceu:olivine_gem', 'gregicsifting:chunk.olivine_stone', true)
                multiSmelt('gtceu:pitchblende_dust', 'gregicsifting:chunk.pitchblende_stone', true)
                multiSmelt('gtceu:uraninite_dust', 'gregicsifting:chunk.uraninite_stone', true)
                multiSmelt('gtceu:graphite_dust', 'gregicsifting:chunk.graphite_stone', true)
                multiSmelt('minecraft:diamond', 'gregicsifting:chunk.diamond_stone', true)
            //Aluminium
                multiSmelt('gtceu:beryllium_ingot', 'gregicsifting:chunk.beryllium_stone', true)
                multiSmelt('minecraft:emerald', 'gregicsifting:chunk.emerald_stone', true)
                multiSmelt('gtceu:thorium_ingot', 'gregicsifting:chunk.thorium_stone', true)
                multiSmelt('3x gtceu:soapstone_dust', 'gregicsifting:chunk.soapstone_stone', true)
                multiSmelt('2x gtceu:talc_dust', 'gregicsifting:chunk.talc_stone', true)
                multiSmelt('gtceu:scheelite_dust', 'gregicsifting:chunk.scheelite_stone', true)
                multiSmelt('gtceu:tungstate_dust', 'gregicsifting:chunk.tungstate_stone', true)
                multiSmelt('gtceu:lithium_dust', 'gregicsifting:chunk.lithium_stone', true)
        //Granite
            //String
                multiSmelt('4x gtceu:apatite_gem', 'gregicsifting:chunk.apatite_stone', true)
                multiSmelt('3x gtceu:tricalcium_phosphate_dust', 'gregicsifting:chunk.tricalcium_phosphate_stone', true)
                multiSmelt('gtceu:bauxite_dust', 'gregicsifting:chunk.bauxite_stone', true)
                multiSmelt('gtceu:ilmenite_dust', 'gregicsifting:chunk.ilmenite_stone', true)
                multiSmelt('minecraft:iron_ingot', 'gregicsifting:chunk.magnetite_stone', true)
                multiSmelt('gtceu:vanadium_magnetite_dust', 'gregicsifting:chunk.vanadium_magnetite_stone', true)
                multiSmelt('minecraft:gold_ingot', 'gregicsifting:chunk.gold_stone', true)
                multiSmelt('2x gtceu:quartzite_gem', 'gregicsifting:chunk.quartzite_stone', true)
                multiSmelt('gtceu:barite_dust', 'gregicsifting:chunk.barite_stone', true)
                multiSmelt('2x gtceu:certus_quartz_gem', 'gregicsifting:chunk.certus_quartz_stone', true)
                multiSmelt('minecraft:copper_ingot', 'gregicsifting:chunk.tetrahedrite_stone', true)
                multiSmelt('gtceu:antimony_ingot', 'gregicsifting:chunk.stibnite_stone', true)
            //Bronze
                multiSmelt('minecraft:copper_ingot', 'gregicsifting:chunk.bornite_stone', true)
                multiSmelt('minecraft:copper_ingot', 'gregicsifting:chunk.chalcocite_stone', true)
                multiSmelt('6x gtceu:lazurite_gem', 'gregicsifting:chunk.lazurite_stone', true)
                multiSmelt('6x gtceu:sodalite_gem', 'gregicsifting:chunk.sodalite_stone', true)
                multiSmelt('6x minecraft:lapis_lazuli', 'gregicsifting:chunk.lapis_stone', true)
                multiSmelt('gtceu:calcite_dust', 'gregicsifting:chunk.calcite_stone', true)
            //Steel
                multiSmelt('gtceu:kyanite_dust', 'gregicsifting:chunk.kyanite_stone', true)
                multiSmelt('2x gtceu:mica_dust', 'gregicsifting:chunk.mica_stone', true)
                multiSmelt('gtceu:pollucite_dust', 'gregicsifting:chunk.pollucite_stone', true)
            //Aluminium
                multiSmelt('gtceu:wulfenite_dust', 'gregicsifting:chunk.wulfenite_stone', true)
                multiSmelt('gtceu:molybdenum_ingot', 'gregicsifting:chunk.molybdenite_stone', true)
                multiSmelt('gtceu:powellite_dust', 'gregicsifting:chunk.powellite_stone', true)
        //Diorite
            //String
                multiSmelt('3x gtceu:alunite_dust', 'gregicsifting:chunk.alunite_stone', true)
            //Bronze
            //Steel
            //Aluminium
        //Netherrack
            //Bronze
                multiSmelt('2x minecraft:copper_ingot', 'gregicsifting:chunk.chalcopyrite_nether', true)
                multiSmelt('2x minecraft:iron_ingot', 'gregicsifting:chunk.iron_nether', true)
                multiSmelt('2x minecraft:iron_ingot', 'gregicsifting:chunk.pyrite_nether', true)
                multiSmelt('2x minecraft:copper_ingot', 'gregicsifting:chunk.copper_nether', true)
                multiSmelt('2x minecraft:iron_ingot', 'gregicsifting:chunk.yellow_limonite_nether', true)
                multiSmelt('2x minecraft:copper_ingot', 'gregicsifting:chunk.malachite_nether', true)
                multiSmelt('2x minecraft:iron_ingot', 'gregicsifting:chunk.magnetite_nether', true)
                multiSmelt('2x gtceu:vanadium_magnetite_dust', 'gregicsifting:chunk.vanadium_magnetite_nether', true)
                multiSmelt('2x minecraft:gold_ingot', 'gregicsifting:chunk.gold_nether', true)
                multiSmelt('4x minecraft:quartz', 'gregicsifting:chunk.nether_quartz_nether', true)
                multiSmelt('2x gtceu:sulfur_dust', 'gregicsifting:chunk.sulfur_nether', true)
                multiSmelt('2x gtceu:zinc_ingot', 'gregicsifting:chunk.sphalerite_nether', true)
                multiSmelt('2x minecraft:copper_ingot', 'gregicsifting:chunk.tetrahedrite_nether', true)
                multiSmelt('2x gtceu:antimony_ingot', 'gregicsifting:chunk.stibnite_nether', true)
            //Aluminium
                multiSmelt('2x gtceu:nickel_ingot', 'gregicsifting:chunk.garnierite_nether', true)
                multiSmelt('2x gtceu:nickel_ingot', 'gregicsifting:chunk.nickel_nether', true)
                multiSmelt('2x gtceu:cobalt_ingot', 'gregicsifting:chunk.cobaltite_nether', true)
                multiSmelt('2x gtceu:nickel_ingot', 'gregicsifting:chunk.pentlandite_nether', true)
                multiSmelt('10x minecraft:redstone', 'gregicsifting:chunk.redstone_nether', true)
                multiSmelt('2x gtceu:ruby_gem', 'gregicsifting:chunk.ruby_nether', true)
                multiSmelt('2x gtceu:cinnabar_gem', 'gregicsifting:chunk.cinnabar_nether', true)
                multiSmelt('2x gtceu:chromite_dust', 'gregicsifting:chunk.chromite_nether', true)
                multiSmelt('10x gtceu:electrotine_dust', 'gregicsifting:chunk.electrotine_nether', true)
                multiSmelt('2x gtceu:topaz_gem', 'gregicsifting:chunk.topaz_nether', true)
                multiSmelt('4x gtceu:blue_topaz_gem', 'gregicsifting:chunk.blue_topaz_nether', true)
        //Endstone
            //Bronze
                multiSmelt('2x gtceu:beryllium_ingot', 'gregicsifting:chunk.beryllium_end', true)
                multiSmelt('4x minecraft:emerald', 'gregicsifting:chunk.emerald_end', true)
                multiSmelt('2x gtceu:thorium_ingot', 'gregicsifting:chunk.thorium_end', true)
            //Steel
                multiSmelt('6x gtceu:grossular_gem', 'gregicsifting:chunk.grossular_end', true)
                multiSmelt('6x gtceu:spessartine_gem', 'gregicsifting:chunk.spessartine_end', true)
                multiSmelt('2x gtceu:manganese_ingot', 'gregicsifting:chunk.pyrolusite_end', true)
                multiSmelt('2x gtceu:tantalite_dust', 'gregicsifting:chunk.tantalite_end', true)
                multiSmelt('2x gtceu:wulfenite_dust', 'gregicsifting:chunk.wulfenite_end', true)
                multiSmelt('2x gtceu:molybdenum_ingot', 'gregicsifting:chunk.molybdenite_end', true)
                multiSmelt('2x gtceu:powellite_dust', 'gregicsifting:chunk.powellite_end', true)
                multiSmelt('2x gtceu:nickel_ingot', 'gregicsifting:chunk.garnierite_end', true)
                multiSmelt('2x gtceu:nickel_ingot', 'gregicsifting:chunk.nickel_end', true)
                multiSmelt('2x gtceu:cobalt_ingot', 'gregicsifting:chunk.cobaltite_end', true)
                multiSmelt('2x gtceu:nickel_ingot', 'gregicsifting:chunk.pentlandite_end', true)
                multiSmelt('6x gtceu:bentonite_dust', 'gregicsifting:chunk.bentonite_end', true)
                multiSmelt('2x gtceu:magnesium_dust', 'gregicsifting:chunk.magnesite_end', true)
                multiSmelt('4x gtceu:olivine_gem', 'gregicsifting:chunk.olivine_end', true)
                multiSmelt('2x gtceu:chromite_dust', 'gregicsifting:chunk.chromite_end', true)
                multiSmelt('2x gtceu:cooperite_dust', 'gregicsifting:chunk.sheldonite_end', true)
                multiSmelt('2x gtceu:scheelite_dust', 'gregicsifting:chunk.scheelite_end', true)
                multiSmelt('2x gtceu:tungstate_dust', 'gregicsifting:chunk.tungstate_end', true)
                multiSmelt('2x gtceu:lithium_dust', 'gregicsifting:chunk.lithium_end', true)
            //Aluminium
                multiSmelt('12x gtceu:lazurite_gem', 'gregicsifting:chunk.lazurite_end', true)
                multiSmelt('12x gtceu:sodalite_gem', 'gregicsifting:chunk.sodalite_end', true)
                multiSmelt('12x minecraft:lapis_lazuli', 'gregicsifting:chunk.lapis_end', true)
                multiSmelt('2x gtceu:calcite_dust', 'gregicsifting:chunk.calcite_end', true)
})
