ServerEvents.recipes(event => {
    function Macerator(Ore, Crushed, Byproduct, Dust, ID){
        event.recipes.gtceu.macerator(`gtceu:macerate_${ID}_ore_chunk_to_crushed_ore`)
        .itemInputs(Ore)
        .itemOutputs(Crushed, Dust)
        .chancedOutput(Byproduct, 1400, 850)
        .duration(400)
        .EUt(2)  
    }
    //Gravel
        //String
            Macerator('gregicsifting:chunk.gypsum_stone', '2x gtceu:gypsum_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:stone_dust', 'stone_gypsum')
            Macerator('gregicsifting:chunk.spodumene_stone', '2x gtceu:spodumene_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:stone_dust', 'stone_spodumene')
            Macerator('gregicsifting:chunk.cassiterite_stone', '4x gtceu:cassiterite_crushed_ore', 'gtceu:tin_dust', 'gtceu:stone_dust', 'stone_cassiterite')
            Macerator('gregicsifting:chunk.coal_stone', '4x gtceu:coal_crushed_ore', 'minecraft:coal', 'gtceu:stone_dust', 'stone_coal')
            Macerator('gregicsifting:chunk.trona_stone', '4x gtceu:trona_crushed_ore', 'gtceu:sodium_dust', 'gtceu:stone_dust', 'stone_trona')
            Macerator('gregicsifting:chunk.fullers_earth_stone', '4x gtceu:fullers_earth_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:stone_dust', 'stone_fullers_earth')
            Macerator('gregicsifting:chunk.basaltic_mineral_stone', '2x gtceu:basaltic_mineral_sand_crushed_ore', 'gtceu:basalt_dust', 'gtceu:stone_dust', 'stone_basaltic_mineral_sand')
            Macerator('gregicsifting:chunk.salt_stone', '4x gtceu:salt_crushed_ore', 'gtceu:rock_salt_gem', 'gtceu:stone_dust', 'stone_salt')
            Macerator('gregicsifting:chunk.granitic_mineral_stone', '2x gtceu:granitic_mineral_sand_crushed_ore', 'gtceu:deepslate_dust', 'gtceu:stone_dust', 'stone_granitic_mineral_sand')
            Macerator('gregicsifting:chunk.tin_stone', '2x gtceu:tin_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'stone_tin')
            Macerator('gregicsifting:chunk.rock_salt_stone', '4x gtceu:rock_salt_crushed_ore', 'gtceu:salt_gem', 'gtceu:stone_dust', 'stone_rock_salt')
            Macerator('gregicsifting:chunk.lepidolite_stone', '4x gtceu:lepidolite_crushed_ore', 'gtceu:lithium_dust', 'gtceu:stone_dust', 'stone_lepidolite')
        //Bronze
            Macerator('gregicsifting:chunk.galena_stone', '2x gtceu:galena_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:stone_dust', 'stone_galena')
            Macerator('gregicsifting:chunk.lead_stone', '2x gtceu:lead_crushed_ore', 'gtceu:silver_dust', 'gtceu:stone_dust', 'stone_lead')
            Macerator('gregicsifting:chunk.silver_stone', '2x gtceu:silver_crushed_ore', 'gtceu:lead_dust', 'gtceu:stone_dust', 'stone_silver')
            Macerator('gregicsifting:chunk.zeolite_stone', '6x gtceu:zeolite_crushed_ore', 'gtceu:calcium_dust', 'gtceu:stone_dust', 'stone_zeolite')
            Macerator('gregicsifting:chunk.glauconite_sand_stone', '6x gtceu:glauconite_sand_crushed_ore', 'gtceu:sodium_dust', 'gtceu:stone_dust', 'stone_glauconite_sand')
            Macerator('gregicsifting:chunk.oilsands_stone', '2x gtceu:oilsands_crushed_ore', 'gtceu:oilsands_dust', 'gtceu:stone_dust', 'stone_oilsands')
            Macerator('gregicsifting:chunk.garnet_sand_stone', '2x gtceu:garnet_sand_crushed_ore', 'gtceu:red_garnet_gem', 'gtceu:stone_dust', 'stone_garnet_sand')
            Macerator('gregicsifting:chunk.asbestos_stone', '6x gtceu:asbestos_crushed_ore', 'gtceu:diatomite_dust', 'gtceu:stone_dust', 'stone_asbestos')
            Macerator('gregicsifting:chunk.diatomite_stone', '2x gtceu:diatomite_crushed_ore', 'gtceu:hematite_dust', 'gtceu:stone_dust', 'stone_diatomite')
        //Steel
            Macerator('gregicsifting:chunk.platinum_stone', '2x gtceu:platinum_crushed_ore', 'gtceu:nickel_dust', 'gtceu:stone_dust', 'stone_platinum')
            Macerator('gregicsifting:chunk.palladium_stone', '2x gtceu:palladium_crushed_ore', 'gtceu:palladium_dust', 'gtceu:stone_dust', 'stone_palladium')
    //Sand
        //Bronze
            Macerator('gregicsifting:chunk.copper_sand', '2x gtceu:copper_crushed_ore', 'gtceu:cobalt_dust', 'gtceu:stone_dust', 'sand_copper')
            Macerator('gregicsifting:chunk.redstone_sand', '10x gtceu:redstone_crushed_ore', 'gtceu:cinnabar_gem', 'gtceu:stone_dust', 'sand_redstone')
            Macerator('gregicsifting:chunk.cinnabar_sand', '2x gtceu:cinnabar_crushed_ore', 'minecraft:redstone', 'gtceu:stone_dust', 'sand_cinnabar')
            Macerator('gregicsifting:chunk.chromite_sand', '2x gtceu:chromite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'sand_chromite')
            Macerator('gregicsifting:chunk.pyrope_sand', '6x gtceu:pyrope_crushed_ore', 'gtceu:red_garnet_gem', 'gtceu:stone_dust', 'sand_pyrope')
            Macerator('gregicsifting:chunk.sapphire_sand', '2x gtceu:sapphire_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:stone_dust', 'sand_sapphire')
            Macerator('gregicsifting:chunk.green_sapphire_sand', '2x gtceu:green_sapphire_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:stone_dust', 'sand_green_sapphire')
        //Steel
            Macerator('gregicsifting:chunk.chalcopyrite_sand', '2x gtceu:chalcopyrite_crushed_ore', 'gtceu:pyrite_dust', 'gtceu:stone_dust', 'sand_chalcopyrite')
            Macerator('gregicsifting:chunk.iron_sand', '2x gtceu:iron_crushed_ore', 'gtceu:nickel_dust', 'gtceu:stone_dust', 'sand_iron')
            Macerator('gregicsifting:chunk.pyrite_sand', '2x gtceu:pyrite_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:stone_dust', 'sand_pyrite')
            Macerator('gregicsifting:chunk.yellow_limonite_sand', '2x gtceu:yellow_limonite_crushed_ore', 'gtceu:nickel_dust', 'gtceu:stone_dust', 'sand_yellow_limonite')
            Macerator('gregicsifting:chunk.malachite_sand', '2x gtceu:malachite_crushed_ore', 'gtceu:goethite_dust', 'gtceu:stone_dust', 'sand_malachite')
            Macerator('gregicsifting:chunk.garnierite_sand', '2x gtceu:garnierite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'sand_garnierite')
            Macerator('gregicsifting:chunk.nickel_sand', '2x gtceu:nickel_crushed_ore', 'gtceu:cobalt_dust', 'gtceu:stone_dust', 'sand_nickel')
            Macerator('gregicsifting:chunk.cobaltite_sand', '2x gtceu:cobaltite_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:stone_dust', 'sand_cobaltite')
            Macerator('gregicsifting:chunk.pentlandite_sand', '2x gtceu:pentlandite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'sand_pentlandite')
            Macerator('gregicsifting:chunk.bentonite_sand', '6x gtceu:bentonite_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:stone_dust', 'sand_bentonite')
            Macerator('gregicsifting:chunk.magnesite_sand', '2x gtceu:magnesite_crushed_ore', 'gtceu:magnesium_dust', 'gtceu:stone_dust', 'sand_magnesite')
            Macerator('gregicsifting:chunk.olivine_sand', '4x gtceu:olivine_crushed_ore', 'gtceu:pyrope_gem', 'gtceu:stone_dust', 'sand_olivine')
        //Aluminium
            Macerator('gregicsifting:chunk.beryllium_sand', '2x gtceu:beryllium_crushed_ore', 'minecraft:emerald', 'gtceu:stone_dust', 'sand_beryllium')
            Macerator('gregicsifting:chunk.emerald_sand', '4x gtceu:emerald_crushed_ore', 'gtceu:beryllium_dust', 'gtceu:stone_dust', 'sand_emerald')
            Macerator('gregicsifting:chunk.thorium_sand', '2x gtceu:thorium_crushed_ore', 'gtceu:uraninite_dust', 'gtceu:stone_dust', 'sand_thorium')
            Macerator('gregicsifting:chunk.grossular_sand', '6x gtceu:grossular_crushed_ore', 'gtceu:yellow_garnet_gem', 'gtceu:stone_dust', 'sand_grossular')
            Macerator('gregicsifting:chunk.spessartine_sand', '6x gtceu:spessartine_crushed_ore', 'gtceu:red_garnet_gem', 'gtceu:stone_dust', 'sand_spessartine')
            Macerator('gregicsifting:chunk.pyrolusite_sand', '2x gtceu:pyrolusite_crushed_ore', 'gtceu:manganese_dust', 'gtceu:stone_dust', 'sand_pyrolusite')
            Macerator('gregicsifting:chunk.tantalite_sand', '2x gtceu:tantalite_crushed_ore', 'gtceu:manganese_dust', 'gtceu:stone_dust', 'sand_tantalite')
    //Andesite
        //Bronze
            Macerator('gregicsifting:chunk.redstone_stone', '10x gtceu:redstone_crushed_ore', 'gtceu:cinnabar_gem', 'gtceu:stone_dust', 'stone_redstone')
            Macerator('gregicsifting:chunk.ruby_stone', '2x gtceu:ruby_crushed_ore', 'gtceu:chromium_dust', 'gtceu:stone_dust', 'stone_ruby')
            Macerator('gregicsifting:chunk.cinnabar_stone', '2x gtceu:cinnabar_crushed_ore', 'minecraft:redstone', 'gtceu:stone_dust', 'stone_cinnabar')
            Macerator('gregicsifting:chunk.chromite_stone', '2x gtceu:chromite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'stone_chromite')
            Macerator('gregicsifting:chunk.almandine_stone', '6x gtceu:almandine_crushed_ore', 'gtceu:red_garnet_gem', 'gtceu:stone_dust', 'stone_almandine')
            Macerator('gregicsifting:chunk.pyrope_stone', '6x gtceu:pyrope_crushed_ore', 'gtceu:red_garnet_gem', 'gtceu:stone_dust', 'stone_pyrope')
            Macerator('gregicsifting:chunk.sapphire_stone', '2x gtceu:sapphire_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:stone_dust', 'stone_sapphire')
            Macerator('gregicsifting:chunk.green_sapphire_stone', '2x gtceu:green_sapphire_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:stone_dust', 'stone_green_sapphire')
            Macerator('gregicsifting:chunk.topaz_stone', '2x gtceu:topaz_crushed_ore', 'gtceu:blue_topaz_gem', 'gtceu:stone_dust', 'stone_topaz')
            Macerator('gregicsifting:chunk.blue_topaz_stone', '4x gtceu:blue_topaz_crushed_ore', 'gtceu:topaz_gem', 'gtceu:stone_dust', 'stone_blue_topaz')
        //Steel
            Macerator('gregicsifting:chunk.chalcopyrite_stone', '2x gtceu:chalcopyrite_crushed_ore', 'gtceu:pyrite_dust', 'gtceu:stone_dust', 'stone_chalcopyrite')
            Macerator('gregicsifting:chunk.iron_stone', '2x gtceu:iron_crushed_ore', 'gtceu:nickel_dust', 'gtceu:stone_dust', 'stone_iron')
            Macerator('gregicsifting:chunk.pyrite_stone', '2x gtceu:pyrite_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:stone_dust', 'stone_pyrite')
            Macerator('gregicsifting:chunk.copper_stone', '2x gtceu:copper_crushed_ore', 'gtceu:cobalt_dust', 'gtceu:stone_dust', 'stone_copper')
            Macerator('gregicsifting:chunk.yellow_limonite_stone', '2x gtceu:yellow_limonite_crushed_ore', 'gtceu:nickel_dust', 'gtceu:stone_dust', 'stone_yellow_limonite')
            Macerator('gregicsifting:chunk.malachite_stone', '2x gtceu:malachite_crushed_ore', 'gtceu:goethite_dust', 'gtceu:stone_dust', 'stone_malachite')
            Macerator('gregicsifting:chunk.bastnasite_stone', '4x gtceu:bastnasite_crushed_ore', 'gtceu:neodymium_dust', 'gtceu:stone_dust', 'stone_bastnasite')
            Macerator('gregicsifting:chunk.monazite_stone', '8x gtceu:monazite_crushed_ore', 'gtceu:thorium_dust', 'gtceu:stone_dust', 'stone_monazite')
            Macerator('gregicsifting:chunk.neodymium_stone', '2x gtceu:neodymium_crushed_ore', 'gtceu:rare_earth_dust', 'gtceu:stone_dust', 'stone_neodymium')
            Macerator('gregicsifting:chunk.garnierite_stone', '2x gtceu:garnierite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'stone_garnierite')
            Macerator('gregicsifting:chunk.nickel_stone', '2x gtceu:nickel_crushed_ore', 'gtceu:cobalt_dust', 'gtceu:stone_dust', 'stone_nickel')
            Macerator('gregicsifting:chunk.cobaltite_stone', '2x gtceu:cobaltite_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:stone_dust', 'stone_cobaltite')
            Macerator('gregicsifting:chunk.pentlandite_stone', '2x gtceu:pentlandite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'stone_pentlandite')
            Macerator('gregicsifting:chunk.bentonite_stone', '6x gtceu:bentonite_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:stone_dust', 'stone_bentonite')
            Macerator('gregicsifting:chunk.magnesite_stone', '2x gtceu:magnesite_crushed_ore', 'gtceu:magnesium_dust', 'gtceu:stone_dust', 'stone_magnesite')
            Macerator('gregicsifting:chunk.olivine_stone', '4x gtceu:olivine_crushed_ore', 'gtceu:pyrope_gem', 'gtceu:stone_dust', 'stone_olivine')
            Macerator('gregicsifting:chunk.pitchblende_stone', '2x gtceu:pitchblende_crushed_ore', 'gtceu:thorium_dust', 'gtceu:stone_dust', 'stone_pitchblende')
            Macerator('gregicsifting:chunk.uraninite_stone', '2x gtceu:uraninite_crushed_ore', 'gtceu:uraninite_dust', 'gtceu:stone_dust', 'stone_uraninite')
            Macerator('gregicsifting:chunk.graphite_stone', '2x gtceu:graphite_crushed_ore', 'gtceu:carbon_dust', 'gtceu:stone_dust', 'stone_graphite')
            Macerator('gregicsifting:chunk.diamond_stone', '2x gtceu:diamond_crushed_ore', 'gtceu:graphite_dust', 'gtceu:stone_dust', 'stone_diamond')
        //Aluminium
            Macerator('gregicsifting:chunk.beryllium_stone', '2x gtceu:beryllium_crushed_ore', 'minecraft:emerald', 'gtceu:stone_dust', 'stone_beryllium')
            Macerator('gregicsifting:chunk.emerald_stone', '4x gtceu:emerald_crushed_ore', 'gtceu:beryllium_dust', 'gtceu:stone_dust', 'stone_emerald')
            Macerator('gregicsifting:chunk.thorium_stone', '2x gtceu:thorium_crushed_ore', 'gtceu:uraninite_dust', 'gtceu:stone_dust', 'stone_thorium')
            Macerator('gregicsifting:chunk.soapstone_stone', '6x gtceu:soapstone_crushed_ore', 'gtceu:silicon_dioxide_dust', 'gtceu:stone_dust', 'stone_soapstone')
            Macerator('gregicsifting:chunk.talc_stone', '4x gtceu:talc_crushed_ore', 'gtceu:clay_dust', 'gtceu:stone_dust', 'stone_talc')
            Macerator('gregicsifting:chunk.scheelite_stone', '2x gtceu:scheelite_crushed_ore', 'gtceu:manganese_dust', 'gtceu:stone_dust', 'stone_scheelite')
            Macerator('gregicsifting:chunk.tungstate_stone', '2x gtceu:tungstate_crushed_ore', 'gtceu:manganese_dust', 'gtceu:stone_dust', 'stone_tungstate')
            Macerator('gregicsifting:chunk.lithium_stone', '2x gtceu:lithium_crushed_ore', 'gtceu:lithium_dust', 'gtceu:stone_dust', 'stone_lithium')
    //Granite
        //String
            Macerator('gregicsifting:chunk.apatite_stone', '8x gtceu:apatite_crushed_ore', 'gtceu:tricalcium_phosphate_dust', 'gtceu:stone_dust', 'stone_apatite')
            Macerator('gregicsifting:chunk.tricalcium_phosphate_stone', '6x gtceu:tricalcium_phosphate_crushed_ore', 'gtceu:apatite_gem', 'gtceu:stone_dust', 'stone_tricalcium_phosphate')
            Macerator('gregicsifting:chunk.bauxite_stone', '2x gtceu:bauxite_crushed_ore', 'gtceu:grossular_gem', 'gtceu:stone_dust', 'stone_bauxite')
            Macerator('gregicsifting:chunk.aluminium_stone', '2x gtceu:aluminium_crushed_ore', 'gtceu:bauxite_dust', 'gtceu:stone_dust', 'stone_aluminium')
            Macerator('gregicsifting:chunk.ilmenite_stone', '2x gtceu:ilmenite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'stone_ilmenite')
            Macerator('gregicsifting:chunk.magnetite_stone', '2x gtceu:magnetite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'stone_magnetite')
            Macerator('gregicsifting:chunk.vanadium_magnetite_stone', '2x gtceu:vanadium_magnetite_crushed_ore', 'gtceu:magnetite_dust', 'gtceu:stone_dust', 'stone_vanadium_magnetite')
            Macerator('gregicsifting:chunk.gold_stone', '2x gtceu:gold_crushed_ore', 'gtceu:copper_dust', 'gtceu:stone_dust', 'stone_gold')
            Macerator('gregicsifting:chunk.quartzite_stone', '4x gtceu:quartzite_crushed_ore', 'gtceu:certus_quartz_gem', 'gtceu:stone_dust', 'stone_quartzite')
            Macerator('gregicsifting:chunk.barite_stone', '2x gtceu:barite_crushed_ore', 'gtceu:barite_dust', 'gtceu:stone_dust', 'stone_barite')
            Macerator('gregicsifting:chunk.certus_quartz_stone', '4x gtceu:certus_quartz_crushed_ore', 'minecraft:quartz', 'gtceu:stone_dust', 'stone_certus_quartz')
            Macerator('gregicsifting:chunk.tetrahedrite_stone', '2x gtceu:tetrahedrite_crushed_ore', 'gtceu:antimony_dust', 'gtceu:stone_dust', 'stone_tetrahedrite')
            Macerator('gregicsifting:chunk.stibnite_stone', '2x gtceu:stibnite_crushed_ore', 'gtceu:antimony_trioxide_dust', 'gtceu:stone_dust', 'stone_stibnite')
        //Bronze
            Macerator('gregicsifting:chunk.bornite_stone', '2x gtceu:bornite_crushed_ore', 'gtceu:pyrite_dust', 'gtceu:stone_dust', 'stone_bornite')
            Macerator('gregicsifting:chunk.chalcocite_stone', '2x gtceu:chalcocite_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:stone_dust', 'stone_chalcocite')
            Macerator('gregicsifting:chunk.lazurite_stone', '12x gtceu:lazurite_crushed_ore', 'gtceu:sodalite_gem', 'gtceu:stone_dust', 'stone_lazurite')
            Macerator('gregicsifting:chunk.sodalite_stone', '12x gtceu:sodalite_crushed_ore', 'gtceu:lazurite_gem', 'gtceu:stone_dust', 'stone_sodalite')
            Macerator('gregicsifting:chunk.lapis_stone', '12x gtceu:lapis_crushed_ore', 'gtceu:lazurite_gem', 'gtceu:stone_dust', 'stone_lapis')
            Macerator('gregicsifting:chunk.calcite_stone', '2x gtceu:calcite_crushed_ore', 'gtceu:calcium_dust', 'gtceu:stone_dust', 'stone_calcite')
        //Steel
            Macerator('gregicsifting:chunk.kyanite_stone', '2x gtceu:kyanite_crushed_ore', 'gtceu:talc_dust', 'gtceu:stone_dust', 'stone_kyanite')
            Macerator('gregicsifting:chunk.mica_stone', '4x gtceu:mica_crushed_ore', 'gtceu:potassium_dust', 'gtceu:stone_dust', 'stone_mica')
            Macerator('gregicsifting:chunk.pollucite_stone', '2x gtceu:pollucite_crushed_ore', 'gtceu:caesium_dust', 'gtceu:stone_dust', 'stone_pollucite')
        //Aluminium
            Macerator('gregicsifting:chunk.wulfenite_stone', '2x gtceu:wulfenite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'stone_wulfenite')
            Macerator('gregicsifting:chunk.molybdenite_stone', '2x gtceu:molybdenite_crushed_ore', 'gtceu:molybdenum_dust', 'gtceu:stone_dust', 'stone_molybdenite')
            Macerator('gregicsifting:chunk.powellite_stone', '2x gtceu:powellite_crushed_ore', 'gtceu:iron_dust', 'gtceu:stone_dust', 'stone_powellite')
    //Diorite
        //String
            Macerator('gregicsifting:chunk.alunite', '6x gtceu:alunite_crushed_ore', 'gtceu:alunite_dust', 'gtceu:stone_dust', 'stone_alunite')
        //Bronze
        //Steel
        //Aluminium
    //Netherrack
        //Bronze
            Macerator('gregicsifting:chunk.chalcopyrite_nether', '4x gtceu:chalcopyrite_crushed_ore', 'gtceu:pyrite_dust', 'gtceu:netherrack_dust', 'nether_chalcopyrite')
            Macerator('gregicsifting:chunk.iron_nether', '4x gtceu:iron_crushed_ore', 'gtceu:nickel_dust', 'gtceu:netherrack_dust', 'nether_iron')
            Macerator('gregicsifting:chunk.pyrite_nether', '4x gtceu:pyrite_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:netherrack_dust', 'nether_pyrite')
            Macerator('gregicsifting:chunk.copper_nether', '4x gtceu:copper_crushed_ore', 'gtceu:cobalt_dust', 'gtceu:netherrack_dust', 'nether_copper')
            Macerator('gregicsifting:chunk.yellow_limonite_nether', '4x gtceu:yellow_limonite_crushed_ore', 'gtceu:nickel_dust', 'gtceu:netherrack_dust', 'nether_yellow_limonite')
            Macerator('gregicsifting:chunk.malachite_nether', '4x gtceu:malachite_crushed_ore', 'gtceu:goethite_dust', 'gtceu:netherrack_dust', 'nether_malachite')
            Macerator('gregicsifting:chunk.magnetite_nether', '4x gtceu:magnetite_crushed_ore', 'gtceu:iron_dust', 'gtceu:netherrack_dust', 'nether_magnetite')
            Macerator('gregicsifting:chunk.vanadium_magnetite_nether', '4x gtceu:vanadium_magnetite_crushed_ore', 'gtceu:magnetite_dust', 'gtceu:netherrack_dust', 'nether_vanadium_magnetite')
            Macerator('gregicsifting:chunk.gold_nether', '4x gtceu:gold_crushed_ore', 'gtceu:copper_dust', 'gtceu:netherrack_dust', 'nether_gold')
            Macerator('gregicsifting:chunk.nether_quartz_nether', '8x gtceu:nether_quartz_crushed_ore', 'gtceu:quartzite_gem', 'gtceu:netherrack_dust', 'nether_nether_quartz')
            Macerator('gregicsifting:chunk.sulfur_nether', '4x gtceu:sulfur_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:netherrack_dust', 'nether_sulfur')
            Macerator('gregicsifting:chunk.sphalerite_nether', '4x gtceu:sphalerite_crushed_ore', 'gtceu:yellow_garnet_gem', 'gtceu:netherrack_dust', 'nether_sphalerite')
            Macerator('gregicsifting:chunk.tetrahedrite_nether', '4x gtceu:tetrahedrite_crushed_ore', 'gtceu:antimony_dust', 'gtceu:netherrack_dust', 'nether_tetrahedrite')
            Macerator('gregicsifting:chunk.stibnite_nether', '4x gtceu:stibnite_crushed_ore', 'gtceu:antimony_trioxide_dust', 'gtceu:netherrack_dust', 'nether_stibnite')
        //Aluminium
            Macerator('gregicsifting:chunk.garnierite_nether', '4x gtceu:garnierite_crushed_ore', 'gtceu:iron_dust', 'gtceu:netherrack_dust', 'nether_garnierite')
            Macerator('gregicsifting:chunk.nickel_nether', '4x gtceu:nickel_crushed_ore', 'gtceu:cobalt_dust', 'gtceu:netherrack_dust', 'nether_nickel')
            Macerator('gregicsifting:chunk.cobaltite_nether', '4x gtceu:cobaltite_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:netherrack_dust', 'nether_cobaltite')
            Macerator('gregicsifting:chunk.pentlandite_nether', '4x gtceu:pentlandite_crushed_ore', 'gtceu:iron_dust', 'gtceu:netherrack_dust', 'nether_pentlandite')
            Macerator('gregicsifting:chunk.redstone_nether', '20x gtceu:redstone_crushed_ore', 'gtceu:cinnabar_gem', 'gtceu:netherrack_dust', 'nether_redstone')
            Macerator('gregicsifting:chunk.ruby_nether', '4x gtceu:ruby_crushed_ore', 'gtceu:chromium_dust', 'gtceu:netherrack_dust', 'nether_ruby')
            Macerator('gregicsifting:chunk.cinnabar_nether', '4x gtceu:cinnabar_crushed_ore', 'minecraft:redstone', 'gtceu:netherrack_dust', 'nether_cinnabar')
            Macerator('gregicsifting:chunk.chromite_nether', '4x gtceu:chromite_crushed_ore', 'gtceu:iron_dust', 'gtceu:netherrack_dust', 'nether_chromite')
            Macerator('gregicsifting:chunk.electrotine_nether', '20x gtceu:electrotine_crushed_ore', 'minecraft:redstone', 'gtceu:netherrack_dust', 'nether_electrotine')
            Macerator('gregicsifting:chunk.topaz_nether', '4x gtceu:topaz_crushed_ore', 'gtceu:blue_topaz_gem', 'gtceu:netherrack_dust', 'nether_topaz')
            Macerator('gregicsifting:chunk.blue_topaz_nether', '8x gtceu:blue_topaz_crushed_ore', 'gtceu:topaz_gem', 'gtceu:netherrack_dust', 'nether_blue_topaz')
    //Endstone
        //Bronze
            Macerator('gregicsifting:chunk.beryllium_end', '4x gtceu:beryllium_crushed_ore', 'minecraft:emerald', 'gtceu:endstone_dust', 'endstone_beryllium')
            Macerator('gregicsifting:chunk.emerald_end', '8x gtceu:emerald_crushed_ore', 'gtceu:beryllium_dust', 'gtceu:endstone_dust', 'endstone_emerald')
            Macerator('gregicsifting:chunk.thorium_end', '4x gtceu:thorium_crushed_ore', 'gtceu:uraninite_dust', 'gtceu:endstone_dust', 'endstone_thorium')
        //Steel
            Macerator('gregicsifting:chunk.grossular_end', '12x gtceu:grossular_crushed_ore', 'gtceu:yellow_garnet_gem', 'gtceu:endstone_dust', 'endstone_grossular')
            Macerator('gregicsifting:chunk.spessartine_end', '12x gtceu:spessartine_crushed_ore', 'gtceu:red_garnet_gem', 'gtceu:endstone_dust', 'endstone_spessartine')
            Macerator('gregicsifting:chunk.pyrolusite_end', '4x gtceu:pyrolusite_crushed_ore', 'gtceu:manganese_dust', 'gtceu:endstone_dust', 'endstone_pyrolusite')
            Macerator('gregicsifting:chunk.tantalite_end', '4x gtceu:tantalite_crushed_ore', 'gtceu:manganese_dust', 'gtceu:endstone_dust', 'endstone_tantalite')
            Macerator('gregicsifting:chunk.wulfenite_end', '4x gtceu:wulfenite_crushed_ore', 'gtceu:iron_dust', 'gtceu:endstone_dust', 'endstone_wulfenite')
            Macerator('gregicsifting:chunk.molybdenite_end', '4x gtceu:molybdenite_crushed_ore', 'gtceu:molybdenum_dust', 'gtceu:endstone_dust', 'endstone_molybdenite')
            Macerator('gregicsifting:chunk.powellite_end', '4x gtceu:powellite_crushed_ore', 'gtceu:iron_dust', 'gtceu:endstone_dust', 'endstone_powellite')
            Macerator('gregicsifting:chunk.garnierite_end', '4x gtceu:garnierite_crushed_ore', 'gtceu:iron_dust', 'gtceu:endstone_dust', 'endstone_garnierite')
            Macerator('gregicsifting:chunk.nickel_end', '4x gtceu:nickel_crushed_ore', 'gtceu:cobalt_dust', 'gtceu:endstone_dust', 'endstone_nickel')
            Macerator('gregicsifting:chunk.cobaltite_end', '4x gtceu:cobaltite_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:endstone_dust', 'endstone_cobaltite')
            Macerator('gregicsifting:chunk.pentlandite_end', '4x gtceu:pentlandite_crushed_ore', 'gtceu:iron_dust', 'gtceu:endstone_dust', 'endstone_pentlandite')
            Macerator('gregicsifting:chunk.bentonite_end', '12x gtceu:bentonite_crushed_ore', 'gtceu:aluminium_dust', 'gtceu:endstone_dust', 'endstone_bentonite')
            Macerator('gregicsifting:chunk.magnesite_end', '4x gtceu:magnesite_crushed_ore', 'gtceu:magnesium_dust', 'gtceu:endstone_dust', 'endstone_magnesite')
            Macerator('gregicsifting:chunk.olivine_end', '8x gtceu:olivine_crushed_ore', 'gtceu:pyrope_gem', 'gtceu:endstone_dust', 'endstone_olivine')
            Macerator('gregicsifting:chunk.chromite_end', '4x gtceu:chromite_crushed_ore', 'gtceu:iron_dust', 'gtceu:endstone_dust', 'endstone_chromite')
            Macerator('gregicsifting:chunk.sheldonite_end', '4x gtceu:cooperite_crushed_ore', 'gtceu:nickel_dust', 'gtceu:endstone_dust', 'endstone_sheldonite')
            Macerator('gregicsifting:chunk.palladium_end', '4x gtceu:palladium_crushed_ore', 'gtceu:palladium_dust', 'gtceu:endstone_dust', 'endstone_palladium')
            Macerator('gregicsifting:chunk.scheelite_end', '4x gtceu:scheelite_crushed_ore', 'gtceu:manganese_dust', 'gtceu:endstone_dust', 'endstone_scheelite')
            Macerator('gregicsifting:chunk.tungstate_end', '4x gtceu:tungstate_crushed_ore', 'gtceu:manganese_dust', 'gtceu:endstone_dust', 'endstone_tungstate')
            Macerator('gregicsifting:chunk.lithium_end', '4x gtceu:lithium_crushed_ore', 'gtceu:lithium_dust', 'gtceu:endstone_dust', 'endstone_lithium')
        //Aluminium
            Macerator('gregicsifting:chunk.naquadah_end', '4x gtceu:naquadah_crushed_ore', 'gtceu:sulfur_dust', 'gtceu:endstone_dust', 'endstone_naquadah')
            Macerator('gregicsifting:chunk.lazurite_end', '24x gtceu:lazurite_crushed_ore', 'gtceu:sodalite_gem', 'gtceu:endstone_dust', 'endstone_lazurite')
            Macerator('gregicsifting:chunk.sodalite_end', '24x gtceu:sodalite_crushed_ore', 'gtceu:lazurite_gem', 'gtceu:endstone_dust', 'endstone_sodalite')
            Macerator('gregicsifting:chunk.lapis_end', '24x gtceu:lapis_crushed_ore', 'gtceu:lazurite_gem', 'gtceu:endstone_dust', 'endstone_lapis')
            Macerator('gregicsifting:chunk.calcite_end', '4x gtceu:calcite_crushed_ore', 'gtceu:calcium_dust', 'gtceu:endstone_dust', 'endstone_calcite')
})
